/*!
 * JSGlib v3.0.1 (minified), JavaScript Library
 *
 * 2011-2015, Adrien Guéret
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * 
 * Date: 25/10/2015
 */
(function(A,H,p){var a={},R=0,ha=function(){return A.requestAnimationFrame||A.webkitRequestAnimationFrame||A.mozRequestAnimationFrame||A.oRequestAnimationFrame||A.msRequestAnimationFrame||function(a){var h=(new Date).getTime(),e=Math.max(0,16-(h-R));A.setTimeout(function(){a(h+e)},e);R=h+e}}(),aa={},X=[],S={WALL:1,SLOPE:2},T=H.createElement("canvas"),ba=T.getContext("2d"),ia=2,L=navigator.userLanguage?navigator.userLanguage:navigator.language,U=L.indexOf("-"),D={STAND:10,STAND_LEFT:11,STAND_RIGHT:12,
	STAND_UP:13,STAND_DOWN:14,STAND_UP_LEFT:15,STAND_UP_RIGHT:16,STAND_DOWN_LEFT:17,STAND_DOWN_RIGHT:18,MOVE:20,MOVE_LEFT:21,MOVE_RIGHT:22,MOVE_UP:23,MOVE_DOWN:24,MOVE_UP_LEFT:25,MOVE_UP_RIGHT:26,MOVE_DOWN_LEFT:27,MOVE_DOWN_RIGHT:28,HURT:30,HURT_LEFT:31,HURT_RIGHT:32,HURT_UP:33,HURT_DOWN:34,HURT_UP_LEFT:35,HURT_UP_RIGHT:36,HURT_DOWN_LEFT:37,HURT_DOWN_RIGHT:38,DEATH:40,DEATH_LEFT:41,DEATH_RIGHT:42,DEATH_UP:43,DEATH_DOWN:44,DEATH_UP_LEFT:45,DEATH_UP_RIGHT:46,DEATH_DOWN_LEFT:47,DEATH_DOWN_RIGHT:48,SLIP:50,
	SLIP_LEFT:51,SLIP_RIGHT:52,SLIP_UP:53,SLIP_DOWN:54,SLIP_UP_LEFT:55,SLIP_UP_RIGHT:56,SLIP_DOWN_LEFT:57,SLIP_DOWN_RIGHT:58},L=-1<U?L.substr(0,U):L,a={get TILES_TYPES(){return S},get USER_LANG(){return L},get KEYWORDS(){return{BREAK:"JSGLIB_BREAK",CONTINUE:"JSGLIB_CONTINUE",NULL:"JSGLIB_NULL",UNDEFINED:"JSGLIB_UNDEFINED",REPEAT:"JSGLIB_REPEAT",REVERSE:"JSGLIB_REVERSE"}},get BACKGROUND(){return{NO_REPEAT:0,REPEAT_X:1,REPEAT_Y:2,REPEAT:3}},get KEY(){return{TAB:9,ENTER:13,SHIFT:16,CTRL:17,CONTROL:17,ALT:18,
	CAPS_LOCK:20,SPACE:32,LEFT:37,UP:38,RIGHT:39,DOWN:40,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90}},get STATE(){return D},addStateConstant:function(c){var h=10,e=0;c=c.toUpperCase();if(D[c])throw new ReferenceError('JSGlib.addStateConstant() => constant "'+c+'" already exists.');a.forEach(D,function(){this>h&&0===this%10&&(h=this)});e=h+=10;D[c]=h;c+="_";D[c+"LEFT"]=++h;D[c+"RIGHT"]=++h;D[c+"UP"]=++h;D[c+"DOWN"]=
	++h;D[c+"UP_LEFT"]=++h;D[c+"UP_RIGHT"]=++h;D[c+"DOWN_LEFT"]=++h;D[c+"DOWN_RIGHT"]=++h;a.Element.prototype["isState"+c]=function(){var a=this.state();return a>=e&&a<=h};return a},isKeyPressed:function(c){c=c.valueOf();return a.forEach(X,function(){if(this.valueOf()==c)return!0})||!1},forceKeyUp:function(c,h){var e=a.removeFromArray(c,X);e&&!h&&a.forEach(aa,function(){this.emitEvent("eventKeyUp",c)});return e},isNull:function(c){return null===c||c==a.KEYWORDS.NULL},isUndefined:function(c){return c===
	p||c==a.KEYWORDS.UNDEFINED},isSet:function(c){return!a.isNull(c)&&!a.isUndefined(c)},getVectorDirection:function(a,h){var e=Math.atan2(-h,a)/(Math.PI/180);return 0>e?e+360:e},removeFromArray:function(c,h,e){e=e||function(a,d){return a==d};return a.forEach(h,function(a){if(e(c,this))return h.splice(a.key,1),!0})||!1},uniqueArray:function(c,h){var e={},k=[];a.forEach(c,function(){e[h?this.getId():this]=this});a.forEach(e,function(){k.push(this)});return k},ajax:function(c){var h=A.XMLHttpRequest?new XMLHttpRequest:
	new A.ActiveXObject("Microsoft.XMLHTTP"),e="",k=!0,d=function(e,c,k){e=k===p?e:k+"["+e+"]";if("object"==typeof c.valueOf()){var g="";a.forEach(c,function(a){g+=d(a.key,this,e)});return g}return e+"="+c+"&"};a.forEach({url:"./",async:!0,type:"GET",dataType:"TEXT",data:{},onAjaxAborted:function(){},onError:function(){},onSuccess:function(){},onComplete:function(){}},function(a){c[a.key]===p&&(c[a.key]=this)});k="POST"==c.type;c.dataType=c.dataType.toUpperCase();if(h)a.forEach(c.data,function(a){e+=
	d(a.key,this)}),e=e.substr(0,e.length-1),h.onreadystatechange=function(){if(4==h.readyState){var a=!0;if(200==h.status||304==h.status)c.onSuccess("JSON"==c.dataType?JSON.parse(h.responseText):"XML"==c.dataType?h.responseXML:h.responseText);else a=!1,c.onError(h);c.onComplete(h,a)}},h.open(c.type,c.url+(k?"":"?"+e),c.async),k&&h.setRequestHeader("Content-type","application/x-www-form-urlencoded"),h.send(k?e:null);else c.onAjaxAborted();return this},random:function(a,h){var e=0;a>h&&(e=h,h=a,a=e);return Math.floor((1+
		h-a)*Math.random())+a},forEach:function(c,h,e){var k="",d=0,l=null,q=function(d,e){var k=c[d];e.key=d;k===p?k=a.KEYWORDS.UNDEFINED:null===k&&(k=a.KEYWORDS.NULL);return h.call(k.valueOf(),e)};e={values:e};if(c instanceof Array||c instanceof A.NodeList)for(d=c.length,k=0;k<d;k++){if(l=q(k,e),l!==p)if(l==a.KEYWORDS.BREAK)break;else if(l!=a.KEYWORDS.CONTINUE)return l}else for(k in c)if(c.hasOwnProperty(k)&&(l=q(k,e),l!==p))if(l==a.KEYWORDS.BREAK)break;else return l},Game:function(c,h){if(!c)throw new ReferenceError("new JSGlib.Game(idContainer) -> please provide a paramater.");
	if(aa[c])throw Error('Container with id "'+c+'" already contains a game.');var e=h?parseInt(h,10):16,k={},d=this,l=null,q=null,n=null,g={},t={},w=[],u=[],m=!1,y=[],M={},V=!1,W=!1,J=new a.Point,N=[],x=[],B=[],z={},F=[],C=[],E={},f=60,ja=0,O=0,Y=[],ca="en",P={},K=0,da=function(){setTimeout(function(){D(!1,function(){var b=this;a.forEach(b.elements,function(){if(d.isElementActive(this)){var v=this.sprite(),r=null,e=null,c=0,f=r=0,g=0,m=null;v&&(r=new a.Point(0,0),e=v.getImage(),f=this.width(),g=this.height(),
		m=this.filter(),v.isTiles()&&r.copy(v.getCurrentTilePosition()),c=r.x(),r=r.y(),b.ctx.globalAlpha=this.opacity()/100,b.ctx.drawImage(e,c,r,f,this.height(),parseInt(this.x(),10),parseInt(this.y(),10),f,g),m&&(a.Drawing.CANVAS_FILTER.width=f,a.Drawing.CANVAS_FILTER.height=g,a.Drawing.CTX_FILTER.drawImage(e,c,r,f,g,0,0,f,g),m.draw(b.ctx,this.position())),b.ctx.globalAlpha=1)}})});a.forEach(Y,function(){var b=this.layer,v=this.object.borderSize(),r=new a.Point(parseInt(this.position.x(),10),parseInt(this.position.y(),
		10)),d=null;b.ctx.globalAlpha=this.object.opacity()/100;b.ctx.fillStyle=this.object.color().getHexadecimal();b.ctx.globalCompositeOperation=this.eraseMode?"destination-out":"source-over";0<v&&(b.ctx.strokeStyle=this.object.borderColor().getHexadecimal(),b.ctx.lineWidth=v,d=new a.Point(r),0<b.ctx.lineWidth%2&&d.substract(.5,.5));this.object.draw(b.ctx,r,d)});ha(da)},1E3/f)},D=function(b,v){var r=n?n.view():null,d=null,e=function(){};null!==r&&(d=r.position(),e=function(){this.canvas.style.left="-"+
		d.x()*this.hspeed+"px";this.canvas.style.top="-"+d.y()*this.vspeed+"px"});a.forEach(C,function(){e.call(this);if(b||this.needRefresh)this.canvas.width=l.getAttribute("data-jsglib-room-width"),this.canvas.height=l.getAttribute("data-jsglib-room-height"),this.needRefresh=!1,v&&v.call(this);var r=this;0<this.animatedTiles.length&&a.forEach(this.animatedTiles,function(){var b=0,a=0;null!==this.sprite.animate()&&(b=this.position.x(),a=this.position.y(),r.tiles[this.sheetName][b][a]=this.sprite.getCurrentTileNumber(),
		r.drawTile(b,a,this.sheetName))})})},ea=function(){a.forEach(F,function(){var b=function(b,a){return b.equals(a)},v=I(this.getLayer());a.removeFromArray(this,v.elements,b);a.removeFromArray(this,N,b);a.removeFromArray(this,x,b);B[this.getId()]=null;v.needRefresh=!0});F.length=0},la=function(){var b=n.getWidth(),a=n.getHeight(),r=n.view(),d=r?r.width():b,r=r?r.height():a;l.setAttribute("data-jsglib-room-width",b);l.setAttribute("data-jsglib-room-height",a);l.style.width=d+"px";l.style.height=r+"px";
		D(!0,Z)},G=function(b,a,r){if(b[a])return r instanceof Array||(r=[r]),b[a].apply(b,r)},Q=function(b,v){var r=!0;a.forEach(x,function(){!1===G(this,b,v)&&(r=!1)});if(!1===r)return!1},L=function(){Y.length=0;O++;fa();G(d,"eventStartStep",[O]);a.forEach(N,function(){d.isElementActive(this)&&ma(this)});G(d,"eventEndStep",[O]);ea();z={};setTimeout(L,1E3/f)},ma=function(b){var v=b.getLayer(),v=I(v),r=b.sprite(),d=null,e=r?r.usedTiles().toString():"";b.prevPosition(b.position()).spriteModified(!1);G(b,"eventStartStep",
		O);r&&(d=r.animate(),null!==d&&d&&G(b,"eventAnimationEnd"));na(b);G(b,"eventStep",O);b.checkMoveToPointCallback();a.forEach(b.getAlarms(),function(a){b.setAlarm(a.key,-1,!0)&&G(b,"eventAlarm"+a.key)});G(b,"eventEndStep",O);r&&0<r.getCurrentMasks().length&&r.usedTiles().toString()!=e&&b.spriteModified(!0);ba(v,function(){return null!==d||b.spriteModified()||!b.prevPosition().equals(b.position())})},na=function(b){var v=b.hspeed(),r=b.vspeed()+b.gravity(),e=parseInt(b.prevPosition().x(),10),f=parseInt(b.prevPosition().y(),
		10),c=!1,g=!1,m=[],c=b.spriteModified(),k=b.sprite(),k=(b.maskColorForSolidCollisions()?!0:!1)&&(k?0<k.getCurrentMasks().length:!1),u=!1,l;if(c||0!==v||0!==r)if(b.vspeed(r),b.x(b.x()+v),b.y(b.y()+r),l=!b.prevPosition().equals(b.position()),b.checkCollisions()&&(c||l)){c=R(b,m);g=T(b,m);if((c||g)&&b.stopOnSolids()){k?a.forEach(m,function(){if(this.concernElement&&("eventCollision"==this.eventName?this.data[1].thisMasks:this.data[1])[b.maskColorForSolidCollisions().getHexadecimal()])return u=!0,a.KEYWORDS.BREAK}):
		u=!0;if(!u)return;b.position().x(e).y(f);c&&ga(b,R);g&&ga(b,T)}a.forEach(m,function(){G(this.target,this.eventName,this.data)})}if(l||V)b.equals(n.viewLinkedElement())?d.checkElementsForActivation():U(b),d.isElementInsideView(b)?G(b,"eventInsideView"):G(b,"eventOutsideView")},fa=function(){var b=n.view(),v,r,d;if(null===b)return!1;r=new a.Point(b.position());v=n.viewLinkedElement();if(null===v)return!1;d=v.x()+v.width()/2-b.width()/2;v=v.y()+v.height()/2-b.height()/2;d=Math.max(d,0);v=Math.max(v,
		0);d=d+b.width()>n.getWidth()?n.getWidth()-b.width():d;v=v+b.height()>n.getHeight()?n.getHeight()-b.height():v;b.position(d,v);V=!r.equals(b.position());return!0},ga=function(b,a){for(var d=0,e=0,e=b.hspeed(),c=b.vspeed()+b.gravity(),f=0<e?1:-1,g=0<c?1:-1,e=Math.abs(e);d<e;d++)if(b.x(b.x()+f),a(b,null,!0)){b.x(b.x()-f);break}d=0;for(e=Math.abs(c);d<e;d++)if(b.y(b.y()+g),a(b,null,!0)){b.y(b.y()-g);break}},R=function(b,v,r){var c=!1,f=b.sprite(),g=f?f.getCurrentMasks():[],f=f?f.getCurrentTilePosition():
		new a.Point,m=f.x(),k=f.y(),u=0<g.length,l={},f=b.getRectangleRepresentation(),n=f.x(),w=f.y(),f=d.isRectangleCollidedWithTiles(f);if(!f)return!1;a.forEach(f,function(b){var d=this.type==S.WALL,v,f,h=function(){return d?(c=!0,a.KEYWORDS[r?"BREAK":"CONTINUE"]):a.KEYWORDS.CONTINUE};if(u)v=new a.Rectangle(this.position,e,e),f=this,a.forEach(g,function(){var b=new a.Rectangle(this.rectangle);b.position().substract(m,k).add(n,w);if(b.isCollidedWithRectangle(v)){if(h()==a.KEYWORDS.BREAK)return a.KEYWORDS.BREAK;
		r||(b=f.layer+"_"+f.position.x()+"_"+f.position.y(),l[b]||(l[b]={tile:f,masks:{}}),l[b].masks[this.color]=!0)}});else if(r||(l[b.key]={tile:this,masks:{}}),h()==a.KEYWORDS.BREAK)return a.KEYWORDS.BREAK});r||a.forEach(l,function(){v.push({target:b,concernElement:!0,eventName:"eventTileCollision",data:[this.tile,this.masks]})});return c},T=function(b,v,d){var e=!1,f=b.sprite(),f=f?f.getCurrentMasks():[],c=b.getId(),g=0<f.length;z[c]||(z[c]={});a.forEach(x,function(){var f=this.getId(),m,k;if(c!=f&&
		this.checkCollisions()&&(!z[c][f]||d)){z[c][f]=!0;z[f]||(z[f]={});z[f][c]=!0;f=b.isCollidedWithElement(this);if(!f)return a.KEYWORDS.CONTINUE;m=(m=this.sprite())?m.getCurrentMasks():[];k=0<m.length;m=this.solid();if(!g&&!k||g&&k&&f.thisHasMasksCollided&&f.otherHasMasksCollided||g&&f.thisHasMasksCollided||k&&f.otherHasMasksCollided)if(d||(v.push({target:this,eventName:"eventCollision",data:[b,{thisMasks:f.otherMasks,otherMasks:f.thisMasks,thisHasMasksCollided:f.otherHasMasksCollided,otherHasMasksCollided:f.thisHasMasksCollided}]}),
			v.push({target:b,concernElement:!0,eventName:"eventCollision",data:[this,f]})),m&&(e=!0,d))return a.KEYWORDS.BREAK}});return e},U=function(b){d.isElementInsideRoom(b)?G(b,"eventMoveInsideRoom"):G(b,"eventMoveOutsideRoom");if(!b.alwaysActive()){var a=d.isElementActive(b),f=d.isElementInsideView(b);!a&&f?d.activateElement(b):a&&!f&&d.deactivateElement(b)}},I=function(b){var d=a.forEach(C,function(){if(this.name==b)return this});if(d)return d;throw new ReferenceError('Layer naming "'+b+'" is not defined for this game.');
	},ba=function(b,a){b.containsElements&&!b.needRefresh&&(a||function(){return!0})()&&(b.needRefresh=!0)},Z=function(){if(!n||!this.backgroundAlias)return!1;var b=d.getImage(this.backgroundAlias),f=b?b.width:0,e=b?b.height:0,c=this.backgroundPosition.x(),g=this.backgroundPosition.y(),m=0,k=0;if(!b)return!1;this.canvas.width=l.getAttribute("data-jsglib-room-width")*Math.max(1,this.hspeed);this.canvas.height=l.getAttribute("data-jsglib-room-height")*Math.max(1,this.vspeed);if(this.backgroundRepeat==a.BACKGROUND.NO_REPEAT)this.ctx.drawImage(b,
		0,0,f,e,c,g,f,e);else if(this.backgroundRepeat==a.BACKGROUND.REPEAT_X)for(;m<this.canvas.width;m+=f)this.ctx.drawImage(b,0,0,f,e,m,g,f,e);else if(this.backgroundRepeat==a.BACKGROUND.REPEAT_Y)for(;k<this.canvas.height;k+=e)this.ctx.drawImage(b,0,0,f,e,c,k,f,e);else for(m=0;m<this.canvas.width;m+=f)for(k=0;k<this.canvas.height;k+=e)this.ctx.drawImage(b,0,0,f,e,m,k,f,e)};this.addClass=function(b){if(!b.name)throw new ReferenceError("Class definition must have a name.");if(E[b.name])throw Error('Class "'+
		b.name+'" is already defined for this game.');var f=null,e=b.name,c={},g=["Element"],m=function(b,d){a.forEach(b,function(b){d?f[b.key]=this:c[b.key]=this})};b.parent=b.parent===p?[]:b.parent;"string"==typeof b.parent&&(b.parent=[b.parent]);f=function(b,f){a.Element.call(this,b.x(),b.y(),f,d)};a.forEach(b.parent,function(){if(!E[this])throw Error('Game.addClass() -> Parent "'+this+'" for class "'+e+'" is not defined in this game.');g=g.concat(E[this]._types);m(E[this].prototype)});g=g.concat(b.parent);
		g.push(e);g=a.uniqueArray(g);Object.defineProperty(c,"_types",{get:function(){return g}});Object.defineProperty(f,"_types",{get:function(){return g}});f["abstract"]=b["abstract"]||!1;b["static"]&&(m(b["static"],!0),delete b["static"]);delete b.parent;delete b["abstract"];delete b.name;m(a.Element.prototype);m(b);f.prototype=c;E[e]=f;return this};this.callParent=function(b,a,f,d){if(d){if(!b.instanceOf(d))throw new TypeError('Game.callParent() -> instance of types "['+b._types+']" is not an instance of "'+
		d+'".');}else d=b._types[b._types.length-2];if(E[d].prototype[a])return f=f===p?[]:f,f instanceof Array||(f=[f]),E[d].prototype[a].apply(b,f);throw new ReferenceError('Game.callParent() -> class "'+d+'" has no methods named "'+a+'".');};this.callStatic=function(b,a,f){if(E[b][a])return f=f===p?[]:f,f instanceof Array||(f=[f]),E[b][a].apply(null,f);throw new ReferenceError('Game.callStatic() -> class "'+b+'" has no methods named "'+a+'".');};this.checkElementsForActivation=function(b){b&&fa();a.forEach(N,
		function(){U(this)});return this};this.orderElementsOnLayer=function(b){I(b).elements.sort(function(b,a){return b.zIndex()-a.zIndex()});return this};this.updateMaxZIndex=function(b){b>K&&(K=b);return this};this.putElementToFirstPlan=function(b){b.zIndex()<K&&b.zIndex(++K);return this};this.emitEvent=function(b,a){Q(b,a);return this};this.instanceCreate=function(b,f,d,e){var c=null,g=c=null,g=0;b instanceof a.Point?(c=b,d=f):c=new a.Point(b,f);if(!E[d])throw new ReferenceError('Game.instanceCreate() -> Class "'+
		d+'" is not defined in this game.');if(E[d]["abstract"])throw Error('Game.instanceCreate() -> Class "'+d+"\" is abstract and can't be instancied.");e=e||"main";g=I(e);if(!g.containsElements)throw Error('Layer "'+e+'" is set to forbid elements inside it. Consider using tiles instead.');c=new E[d](c,e);N.push(c);x.push(c);B[c.getId()]=!0;g.elements.push(c);g.needRefresh=!0;g=c.zIndex();g>K&&(K=g);G(c,"eventCreate");return c};this.instanceDestroy=function(b,a){a||G(b,"eventDestroy");F.push(b);return this};
	this.isElementInsideView=function(b){var a=n.view();return a?b.getRectangleRepresentation().isCollidedWithRectangle(a):!0};this.isElementInsideRoom=function(b){return b.getRectangleRepresentation().isCollidedWithRectangle(new a.Rectangle(0,0,n.getWidth(),n.getHeight()))};this.isElementActive=function(b){return B[b.getId()]};this.activateElement=function(b){this.isElementActive(b)||(x.push(b),B[b.getId()]=!0);return this};this.deactivateElement=function(b){this.isElementActive(b)&&(a.removeFromArray(b,
		x,function(b,a){return b.equals(a)}),B[b.getId()]=!1);return this};this.getTilesSize=function(){return e};this.load=function(b,f,c){f=f===p?!0:f;b=b||{};b.images=b.images||{};b.sounds=b.sounds||{};b.tiles=b.tiles||[];b.rooms=b.rooms||[];var m=b.tiles.length+b.rooms.length,u=0,n=function(){var b=parseInt(100*u/m,10),a=I("main").ctx;l.setAttribute("data-jsglib-room-width",500);l.setAttribute("data-jsglib-room-height",30);l.style.width="500px";l.style.height="30px";D(!0);a.fillStyle="#ff0000";a.rect(0,
		0,500*b/100,30);a.fill();a.fillStyle="#000";a.font="bold 20px Calibri";a.fillText(b+"%",250,20)},w=function(){f&&n();c&&u==m&&setTimeout(function(){c.call(d)},500)};a.forEach(b.images,function(){m++});a.forEach(b.sounds,function(){m++});0<m?(f&&n(0,m),a.forEach(b.images,function(b){var a=new Image;a.src=this;g[b.key]=a;a.onload=function(){u++;w()}}),a.forEach(b.sounds,function(b){var f=H.createElement("audio");f.preload="auto";l.appendChild(f);a.forEach(this,function(){var b=H.createElement("source"),
		a="";switch(this.substring(this.lastIndexOf(".")+1)){case "mp3":a="audio/mpeg";break;case "wav":a="audio/wav";break;case "ogg":a="audio/ogg"}0<f.canPlayType(a).length&&(b.src=this,f.appendChild(b))});t[b.key]={elem:f,volume:1,onEnd:null,loop:!0};u++;w()}),a.forEach(b.tiles,function(){a.ajax({url:this,async:!1,dataType:"JSON",onError:function(){throw Error('An Ajax error occurs while loading tiles "'+this+'".');},onSuccess:function(b){a.forEach(b,function(b){m++;var f=d.getImage(this.image),c=new a.Sprite(f),
		g=this,v=function(b,a){return function(f){return b*f+a}},r=function(b){c.makeTiles(e,e,g.separation);a.forEach(g.slopes,function(b){g.slopes[b.key]["function"]=v(this["function"][0],this["function"][1])});k[b]={sprite:c,animations:g.animations,slopes:g.slopes,separation:g.separation,types:{}};a.forEach(g.types,function(f){var d=f.key;S[d]||(S[d]=++ia);a.forEach(this,function(){k[b].types[this]=S[d]})});u++;w()};(function(b){f.complete?r(b):f.addEventListener("load",function(){r(b)})})(b.key)});u++}})}),
		a.forEach(b.rooms,function(){a.ajax({url:this,async:!1,dataType:"JSON",onError:function(){throw Error('An Ajax error occurs while loading level "'+this+'".');},onSuccess:function(b){var f=new a.Room(b.name,b.width,b.height);0<b.view_w&&0<b.view_h&&f.view(b.view_x,b.view_y,b.view_w,b.view_h);d.addRooms(f);M[b.name]={elements:b.elements,tiles:b.tiles};u++;w()}})})):c&&c.call(d);return this};this.getImage=function(b){return g[b]||null};this.soundIsPlaying=function(b){return b?a.forEach(w,function(){if(this==
		b)return!0})||!1:0<w.length};this.playSound=function(b,f,e){var c=t[b],g=null;if(c&&c.elem)g=c.elem,this.soundIsPlaying(b)?g.currentTime=0:(w.push(b),t[b].onEnd=e,t[b].loop=f,a.removeFromArray(b,u)),m&&(g.volume=0),g.play(),g.addEventListener("ended",function ka(){g.removeEventListener("ended",ka,!1);a.removeFromArray(b,w);e&&e.apply(d);f&&(g.currentTime=0,d.playSound(b,!0,e))},!1);else throw new ReferenceError('Game.playSound() -> Sound "'+b+'" is not defined in this game.');return this};this.stopSound=
		function(b,f,e){var c=t[b],g=null;if(c&&c.elem)g=c.elem,this.soundIsPlaying(b)&&(g.pause(),f?u.push(b):g.currentTime=0,a.removeFromArray(b,w),e&&g.onended&&g.onended.apply(d));else throw new ReferenceError('Game.stopSound() -> Sound "'+b+'" is not defined in this game.');return this};this.stopAllSounds=function(b,a){for(;0<w.length;)this.stopSound(w[0],b,a);return this};this.replayPausedSounds=function(){for(;0<u.length;){var b=u[0];this.playSound(b,t[b].loop,t[b].onEnd)}return this};this.setSoundVolume=
		function(b,a){if(!m){var f=t[b];if(f)f.elem.volume=(Math.min(100,Math.max(0,a))/100).toFixed(1);else throw new ReferenceError('Game.setSoundVolume() -> Sound "'+b+'" is not defined in this game.');}return this};this.muteSounds=function(b){if(b===p)return m;(m=!!b)?a.forEach(t,function(){this.volume=this.elem.volume;this.elem.volume=0}):a.forEach(t,function(){this.elem.volume=this.volume});return this};this.toggleMuteSounds=function(){this.muteSounds(!m);return this};this.defaultLang=function(b){if(!b)return ca;
		ca=b;return this};this.defineTranslation=function(b){a.forEach(b,function(b){P[b.key]||(P[b.key]={});a.forEach(this,function(a){P[b.key][a.key]=this})});return this};this.getTranslation=function(b,f,d){if(P[b]){d=d||a.USER_LANG;var e=P[b][d];e||(e=P[b][ca]);return e?(f&&a.forEach(f,function(b){e=e.replace(new RegExp("%"+b.key,"g"),this)}),e):"["+b+"]["+d+"]"}throw new ReferenceError('Game.getTranslation() -> Text "'+b+'" is not defined in this game.');};this.isTileAnimated=function(b,f){var d=k[b],
		e=!1;if(!d)throw new ReferenceError('Game.isTileAnimated(): there is no tiles with name "'+b+'"');e=a.forEach(d.animations,function(b){if(a.forEach(this.tiles,function(){if(f.valueOf()==this)return!0}))return b.key});return e===p?!1:e};this.isTileSlope=function(b,f){var d=k[b],e=!1;if(!d)throw new ReferenceError('Game.isTileSlope() -> there is no tiles with name "'+b+'"');a.forEach(d.slopes,function(){if(a.forEach(this.tiles,function(){if(f.valueOf()==this)return!0}))return e=this["function"],a.KEYWORDS.BREAK});
		return e};this.createLayer=function(b,f){if(!b)throw new ReferenceError("Game.createLayer() -> name of new layer undefined.");var d=H.createElement("canvas"),c=d.getContext("2d"),g=ja++;d.id="jsglib-layer-"+b;d.style.position="absolute";d.style.zIndex=g;d.style.left=0;d.style.top=0;d.width=0;d.height=0;c.textBaseline="top";l.appendChild(d);C.push({name:b,canvas:d,ctx:c,elements:[],tiles:{},animatedTiles:[],spritesTiles:{},needRefresh:!0,hspeed:1,vspeed:1,containsElements:f||!1,backgroundAlias:null,
		backgroundRepeat:a.BACKGROUND.REPEAT,backgroundPosition:new a.Point,drawTile:function(b,f,d){var c=this.tiles[d][b][f],g=new a.Point(0,0);f*=e;b*=e;0<c&&(this.spritesTiles[d].usedTiles([c]),g.copy(this.spritesTiles[d].getCurrentTilePosition()),this.ctx.clearRect(f,b,e,e),this.ctx.drawImage(this.spritesTiles[d].getImage(),g.x(),g.y(),e,e,f,b,e,e))}});return this};this.getLayers=function(){var b=[];a.forEach(C,function(){b.push(this.name)});return b};this.isRectangleCollidedWithTiles=function(b){var f=
		[],d=b.x(),c=b.y(),g=b.width();b=b.height();var m,u,l=Math.floor(d/e),n=Math.floor(c/e),w=Math.floor((d+g-1)/e),h=Math.floor((c+b-1)/e);a.forEach(C,function(){var b=this;for(m=l;m<=w;m++)for(u=n;u<=h;u++)a.forEach(b.tiles,function(d){if(this[u]&&this[u][m]){d=k[d.key].types[this[u][m]];var c,g;d&&(c=m*e,g=u*e,f.push({number:this[u][m],type:d,layer:b.name,position:new a.Point(c,g)}))}})});return 0<f.length?f:!1};this.setLayerBackgroundPosition=function(b,f,d){var e=I(b);f instanceof a.Point?e.backgroundPosition.copy(f):
		e.backgroundPosition.x(f).y(d);Z.call(e,b);return this};this.setLayerBackgroundRepeat=function(b,a){var f=I(b);f.backgroundRepeat=a;Z.call(f,b);return this};this.setLayerBackgroundAlias=function(b,a){var f=I(b);f.backgroundAlias=a;Z.call(f,b);return this};this.setLayerSpeed=function(b,a,f){b=I(b);b.hspeed=parseFloat(a||0,10);b.vspeed=parseFloat(f||0,10);return this};this.orderLayers=function(b){a.forEach(b,function(b){I(this).canvas.style.zIndex=b.key});return this};this.getScreen=function(){var b=
		H.createElement("canvas"),f=b.getContext("2d"),d=n.view(),e=d?d.position():new a.Point,c=d?d.width():n.getWidth(),g=d?d.height():n.getHeight();b.width=c;b.height=g;C.sort(function(b,a){return b.canvas.style.zIndex-a.canvas.style.zIndex});a.forEach(C,function(){f.drawImage(this.canvas,parseInt(e.x()*this.hspeed,10),parseInt(e.y()*this.vspeed,10),c,g,0,0,c,g)});return b.toDataURL()};this.getTileType=function(b,f,d,c){d=I(d);var g=0;b=Math.floor(b/e);f=Math.floor(f/e);if(c)return d.tiles[c]&&d.tiles[c][f]&&
	d.tiles[c][f][b]?k[c].types[d.tiles[c][f][b]]:0;a.forEach(d.tiles,function(d){if(this[f]&&this[f][b])return g=k[d.key].types[this[f][b]],a.KEYWORDS.BREAK});return g};this.run=function(){if(0===y.length)throw new RangeError("The game can't be launched because it contains no rooms.");W||(W=!0,l.addEventListener("mousemove",function(b){var a,f=(a=n.view())?a.x():0,d=a?a.y():0;b.targetTouches?(a=b.targetTouches[0].pageX,b=b.targetTouches[0].pageY):(a=b.pageX,b=b.pageY);a-=this.getBoundingClientRect().left+
		(A.pageXOffset||this.scrollLeft)-(this.clientLeft||0);b-=this.getBoundingClientRect().top+(A.pageYOffset||this.scrollTop)-(this.clientTop||0);b+=d;J.x(a+f).y(b)},!1),l.addEventListener("mousedown",function(b){Q("eventMouseDown",0===b.button?37:39)}),l.addEventListener("mouseup",function(b){var f=Q("eventMouseUp",0===b.button?37:39);b=f===p?!1:!f;var e=[],f=!0;a.forEach(x,function(){var b=this.isMouseOver(),a=G(this,"eventClick",[b]);f=f&&a;b&&e.push(this)});G(d,"eventClick",[e]);f=f===p?!1:!f;l.oncontextmenu=
		b||f?function(){return!1}:null}),H.addEventListener("keydown",function(b){b=b||A.event;var f=b.which||b.keyCode,d=!1,e=null;a.isKeyPressed(f)||(X.push(f),e=Q("eventKeyDown",f),d=e===p?!1:!e);e=Q("eventKeyPressed",f);e=e===p?!1:!e;if(d||e)return b.preventDefault(),!1}),H.addEventListener("keyup",function(b){b=b||A.event;b=b.which||b.keyCode;a.removeFromArray(b,X)&&Q("eventKeyUp",b)}),H.addEventListener("keypress",function(b){b=b||A.event;var a=b.which||b.keyCode;if(37<=a&&40>=a)return b.preventDefault(),
		!1}));this.goToFirstRoom();da();L();return this};this.getMouse=function(){return J};this.addRooms=function(b){if(b instanceof Array)a.forEach(b,function(){if(this instanceof a.Room)y.push(this);else throw new TypeError("Trying to add objects which are not instances of Room.");});else if(b instanceof a.Room)y.push(b);else throw new TypeError("Game.addRomms() -> trying to add an object which is not an instance of Room.");return this};this.getRoom=function(b){return a.forEach(y,function(){if(this.getName()==
			b)return this})||null};this.getRooms=function(){return y};this.getCurrentRoom=function(){return n};this.goToFirstRoom=function(){return this.goToRoom(y[0])};this.goToLastRoom=function(){return this.goToRoom(y[y.length-1])};this.goToNextRoom=function(){var b=0;a.forEach(y,function(f){if(this.getName()==n.getName())return b=f.key+1,a.KEYWORDS.BREAK});b>=y.length&&(b=0);return this.goToRoom(y[b])};this.goToPrevRoom=function(){var b=0;a.forEach(y,function(f){if(this.getName()==n.getName())return b=f.key-
		1,a.KEYWORDS.BREAK});return 0>b?this.goToLastRoom():this.goToRoom(y[b])};this.restartRoom=function(){return this.goToRoom(n)};this.goToRoom=function(b){var f=null,f={};if(b instanceof a.Room)n=b;else if(f=this.getRoom(b))n=f;else throw new ReferenceError("This game doesn't have a room with name \""+b+'".');a.forEach(N,function(){d.instanceDestroy(this,!0)});ea();a.forEach(C,function(){this.animatedTiles.length=0;this.elements.length=0});Y.length=0;la();if(f=M[n.getName()])a.forEach(f.elements,function(){d.instanceCreate(this.x,
		this.y,this["class"],this.layer)}),a.forEach(f.tiles,function(b){var f=I(b.key);a.forEach(this,function(b){var c=b.key,g=k[c];g.sprite&&(f.tiles[c]=this,f.spritesTiles[c]=g.sprite,a.forEach(this,function(b){a.forEach(this,function(m){var k=this,u=null,l=d.isTileAnimated(c,k),n=0;f.drawTile(b.key,m.key,c);!1!==l&&(n=g.animations[l].speed)&&(u=(new a.Sprite(f.spritesTiles[c].getImage())).makeTiles(e,e,g.separation).usedTiles(g.animations[l].tiles).imagespeed(n),a.forEach(u.usedTiles(),function(b){if(this==
		k)return u.imageindex(b.key),!0}),f.animatedTiles.push({sheetName:c,position:new a.Point(b.key,m.key),sprite:u}))})}))})});n.eventStart();return this};this.fps=function(b){if(b===p)return f;f=parseInt(b,10);return this};this.getInstancesByType=function(b){if(!E[b])throw new ReferenceError('Game.getInstancesByType() -> Class "'+b+'" is not defined in this game.');var f=[];a.forEach(x,function(){this.instanceOf(b)&&f.push(this)});return f};this.getInstancesIn=function(b){var f=[];a.forEach(x,function(){this.getRectangleRepresentation().isCollidedWithRectangle(b)&&
	f.push(this)});return f};this.getInstanceNearest=function(b,f,d,e){var c=null,g=-1,m=0;if((f=f||!1)&&!E[f])throw new ReferenceError('Game.getInstanceNearest() -> Class "'+f+'" is not defined in this game.');d=d||null;a.forEach(x,function(){if(f&&!this.instanceOf(f)||d&&this.equals(d))return a.KEYWORDS.CONTINUE;m=b.getDistanceTo(this.getCenter());(0>g||m<g)&&(!e||e&&e>=m)&&(g=m,c=this)});return c};this.instanceNumber=function(b){if(!E[b])throw new ReferenceError('Game.instanceNumber() -> Class "'+
		b+'" is not defined in this game.');return this.getInstancesByType(b).length};this.totalOfInstances=function(b){if(!b)return x.length;if(!E[b])throw new ReferenceError('Game.totalOfInstances() -> Class "'+b+'" is not defined in this game.');return this.getInstancesByType(b).length};this.isMouseOver=function(b){return J.isInRectangle(b.getRectangleRepresentation())};this.drawObject=function(b,f,d,e,c){if(!b)throw new ReferenceError("Game.drawObject() -> given object seems to not exist.");var g=I(f);
		if(c||0<b.opacity())g=I(f),e&&(g.needRefresh=!0),d=d||new a.Point,Y.push({object:b,position:d,layer:g,eraseMode:c});return this};this.eraseObject=function(b,a,f){if(!b)throw new ReferenceError("Game.eraseObject() -> given object seems to not exist.");return this.drawObject(b,a,f,!1,!0)};l=H.getElementById(c);if(!l)throw new ReferenceError('new JSGlib.Game("'+c+'") -> id "'+c+'" does not exist.');l.style.overflow="hidden";l.style.display="block";q=A.getComputedStyle(l);if("static"==q.position||0===
		q.position.length)l.style.position="relative";aa[c]=this;this.createLayer("main",!0)},Element:function(c,h,e,k){a.Element._isLoaded||(a.Element._isLoaded=!0,a.Element._lastId=0);var d=++a.Element._lastId,l=new a.Point(c,h),q=new a.Point(c,h),n=0,g=0,t=0,w=100,u=new a.Rectangle(c,h),m=null,y=a.STATE.STAND,M=!1,V=!1,W=!1,J=!0,N=!0,x=null,B={},z=null,F=d,C=!1,E=null;this.getId=function(){return d};this.getGame=function(){return k};this.zIndex=function(a){if(a===p)return F;a!=F&&(F=parseInt(a,10),k.orderElementsOnLayer(e).updateMaxZIndex(F));
	return this};this.putToFirstPlan=function(){k.putElementToFirstPlan(this);return this};this.destroy=function(a){k.instanceDestroy(this,a);return this};this.getRectangleRepresentation=function(){return u};this.active=function(a){if(a)k.activateElement(this);else if(!1===a)k.deactivateElement(this);else return k.isElementActive(this);return this};this.callParent=function(a,d,e){return k.callParent(this,a,d,e)};this.instanceNearest=function(a,d){return k.getInstanceNearest(this.getCenter(),a,this,d)};
	this.isInsideRoom=function(){return k.isInsideRoom(this)};this.isInsideView=function(){return k.isInsideView(this)};this.isMouseOver=function(){return k.isMouseOver(this)};this.x=function(a){if(a===p)return u.x();u.x(a);return this};this.y=function(a){if(a===p)return u.y();u.y(a);return this};this.width=function(a){if(a===p)return m?m.isTiles()?m.getTilesWidth():m.getWidth():u.width();u.width(a);return this};this.height=function(a){if(a===p)return m?m.isTiles()?m.getTilesHeight():m.getHeight():u.height();
		u.height(a);return this};this.position=function(f,d){if(f===p)return u.position();f instanceof a.Point?u.position().copy(f):u.position().x(f).y(d);M=!0;return this};this.prevPosition=function(a){if(a===p)return q;q.copy(a);return this};this.prevX=function(){return q.x()};this.prevY=function(){return q.y()};this.startPosition=function(){return l};this.startX=function(){return l.x()};this.startY=function(){return l.y()};this.setAlarm=function(a,d,e){d=parseInt(d,10);if(e)return B[a]+=d,1>B[a]?(delete B[a],
		!0):!1;B[a]=d;return this};this.cancelAlarm=function(a){delete B[a];return this};this.getAlarms=function(){return B};this.filter=function(a){if(!a)return x;x=a;return this};this.getCenter=function(){return u.getCenter()};this.gravity=function(a){if(a===p)return n;n=parseFloat(a,10);return this};this.hspeed=function(a){if(a===p)return g;g=parseFloat(a,10);return this};this.vspeed=function(a){if(a===p)return t;t=parseFloat(a,10);return this};this.getDirection=function(){return a.getVectorDirection(g,
		t)};this.moveToDirection=function(a,d){a=(360-a)*Math.PI/180;g=d*Math.cos(a);t=d*Math.sin(a);return this};this.moveToPoint=function(f,d,e){var c=parseInt(f.x(),10);f=parseInt(f.y(),10);var g=c-parseInt(this.x(),10),m=f-parseInt(this.y(),10);e&&(z={x:c,y:f,fromLeft:0<g,fromTop:0<m,callback:e});return this.moveToDirection(a.getVectorDirection(g,m),d)};this.setPath=function(f,d,e){if(f[0]instanceof a.Point||f[0].point){var c=this,g=null;(function K(m){C=!0;if(g=f[m]instanceof a.Point?f[m]:f[m].point)c.moveToPoint(g,
		d,function(){f[m].callback&&f[m].callback.apply(c);if(f[++m])K(m);else if(e)if("string"==typeof e)switch(e){case a.KEYWORDS.REPEAT:K(0);break;case a.KEYWORDS.REVERSE:f.reverse(),f.push(f.shift()),K(0)}else C=!1,e.apply(c);else C=!1});else throw new TypeError('Element.setPath() -> point at index "'+m+'" seems to not exist.');})(0)}else throw new TypeError('Element.setPath() -> first parameter must be an array of JSGlib.Point or an array of objects having a property "point" which is an instance of JSGlib.Point.');
		return this};this.cancelMoveToPointCallBack=function(){z=null;C=!1;return this};this.checkMoveToPointCallback=function(){if(z){var a=Math.floor(this.x()),d=Math.floor(this.y()),e=Math.abs(g),c=Math.abs(t);0<e&&.1>e&&(g=0,this.x(z.x));0<c&&.1>c&&(t=0,this.y(z.y));(z.fromLeft&&a>=z.x||!z.fromLeft&&a<=z.x)&&(z.fromTop&&d>=z.y||!z.fromTop&&d<=z.y)&&(z.callback.apply(this),C||(z=null))}return this};this.opacity=function(a){if(a===p)return w;w=parseInt(a,10);M=!0;return this};this.solid=function(a){if(a===
		p)return W;W=a;return this};this.checkCollisions=function(a){if(a===p)return J;J=a;return this};this.stopOnSolids=function(a){if(a===p)return N;N=a;return this};this.maskColorForSolidCollisions=function(d){if(!d)return E;E=new a.Color(d);return this};this.getLayer=function(){return e};this.sprite=function(d,e,c,g,l){if(!d)return m;d instanceof a.Sprite?m=d:(m=new a.Sprite(k.getImage(d)),e&&(m.makeTiles(e,c,g),l&&m.masks(k.getImage(l))));M=!0;u.height(m.isTiles()?m.getTilesHeight():m.getHeight());
		u.width(m.isTiles()?m.getTilesWidth():m.getWidth());return this};this.spriteModified=function(a){if(a===p)return M;M=a;return this};this.alwaysActive=function(a){if(a===p)return V;V=a;return this};this.equals=function(a){return a?a.getId?d==a.getId():!1:!1};this.instanceOf=function(d){return!!a.forEach(this._types,function(){if(this==d)return!0})};this.isCollidedWithElement=function(d){var e=this,c=m?m.getCurrentMasks():[],g=d.sprite(),k=g?g.getCurrentMasks():[],l=m.getCurrentTilePosition(),n=g?g.getCurrentTilePosition():
		new a.Point,w=null,g=0===c.length,h=0===k.length,y=null,q={thisMasks:{},otherMasks:{},thisHasMasksCollided:!1,otherHasMasksCollided:!1},p=function(d,e,f,c,g){a.forEach(d,function(){var d=new a.Rectangle(this.rectangle);d.x(d.x()+e.x()-c.x()).y(d.y()+e.y()-c.y());f.getRectangleRepresentation().isCollidedWithRectangle(d)&&(q[g+"Masks"][this.color]=!0,q[g+"HasMasksCollided"]=!0)})};return u.isCollidedWithRectangle(d.getRectangleRepresentation())?(g||h?g&&h||(g?p(k,d,e,n,"other"):p(c,e,d,l,"this")):a.forEach(c,
		function(){y=new a.Rectangle(this.rectangle);y.x(y.x()+e.x()-l.x()).y(y.y()+e.y()-l.y());w=this;a.forEach(k,function(){var e=new a.Rectangle(this.rectangle);e.x(e.x()+d.x()-n.x()).y(e.y()+d.y()-n.y());y.isCollidedWithRectangle(e)&&(q.thisMasks[w.color]=!0,q.otherMasks[this.color]=!0,q.thisHasMasksCollided=!0,q.otherHasMasksCollided=!0)})}),q):!1};this.getMask=function(d){var e=this.sprite(),c=e?e.getCurrentMasks():[],g=null,m=null,g=null;0<c.length&&(g=d?a.forEach(c,function(){if(this.color===d)return this}):
		c[0])&&(m=new a.Rectangle(g.rectangle),g=e.getCurrentTilePosition(),m.x(m.x()-g.x()).y(m.y()-g.y()));m||(m=(new a.Rectangle(u)).x(0).y(0));return m};this.state=function(a){if(a===p)return y;y=a;return this};this.isStateSTAND=function(){return y>=a.STATE.STAND&&y<=a.STATE.STAND_DOWN_RIGHT};this.isStateMOVE=function(){return y>=a.STATE.MOVE&&y<=a.STATE.MOVE_DOWN_RIGHT};this.isStateHURT=function(){return y>=a.STATE.HURT&&y<=a.STATE.HURT_DOWN_RIGHT};this.isStateDEATH=function(){return y>=a.STATE.DEATH&&
		y<=a.STATE.DEATH_DOWN_RIGHT};this.isStateSLIP=function(){return y>=a.STATE.SLIP&&y<=a.STATE.SLIP_DOWN_RIGHT};this.isStateLEFT=function(){var a=y%10;return 1==a||5==a||7==a};this.isStateRIGHT=function(){var a=y%10;return 2==a||6==a||8==a};this.isStateUP=function(){var a=y%10;return 3==a||5==a||6==a};this.isStateDOWN=function(){var a=y%10;return 4==a||7==a||8==a}},Sprite:function(c){if(!c)throw new ReferenceError("new Sprite() -> no image provided.");var h=[],e=[],k=0,d=0,l=0,q=.1,n=0,g=null,t=function(a,
																																																																																																																																  e){var m=e.x(),l=e.y(),n=c.height%d,q=c.width%k,p=0,p=0;0<h.length&&(m=Math.round(Math.max(0,m-q)/k),l=Math.round(Math.max(0,l-n)/d),p=(c.width-q)/k,p=(.5==m?0:m)+(.5==l?0:l)*p+1);g[p]||(g[p]=[]);g[p].push({color:a,rectangle:e})};this.getImage=function(){return c};this.getWidth=function(){return c.width};this.getHeight=function(){return c.height};this.getTilesWidth=function(){return k};this.getTilesHeight=function(){return d};this.getTilesSeparation=function(){return l};this.isTiles=function(){return 0<
	h.length};this.animate=function(){if(!this.isTiles()||0===q)return null;var a=n,d=parseInt(n,10),c=e.length;if(1==c)return null;a+=q;if(a>c)return n=0,1<c?!0:null;if(parseInt(a,10)>d)return n=d+1,!1;n=a;return null};this.makeTiles=function(c,g,m){m=m||0;for(var n=this.getWidth(),q=this.getHeight(),p=0,t=0,J=0,t=0;t<q;t+=g){J=t/g;h[J]=[];for(p=0;p<n;p+=c)h[J][p/c]=new a.Point(p+p/c*m,t+t/g*m),n-=m;n=this.getWidth();q-=m}k=c;d=g;l=m;e=[1];return this};this.usedTiles=function(a){if(!a)return e;a.toString()!=
e.toString()&&(e=a,this.imageindex(0));return this};this.imagespeed=function(a){if(a===p)return q;q=a;return this};this.imageindex=function(a){if(a===p)return n;n=a;return this};this.getCurrentMasks=function(){if(g){var a=this.getCurrentTileNumber();return g[a]?g[a]:[]}return[]};this.masks=function(d){if(!d)return g;var e=H.createElement("canvas"),c=e.getContext("2d"),k=[],l=null,n=null,h=null,q=null,p=null,x=0,B=0,z=a.KEYWORDS.NULL,F=0,C=0;g?g.length=0:g=[];e.width=d.width;e.height=d.height;c.drawImage(d,
	0,0);p=c.getImageData(0,0,d.width,d.height);for(C=p.data.length;F<C;F+=4)n=p.data[F],h=p.data[F+1],q=p.data[F+2],x=F/4,B=Math.floor(x/e.width),x%=e.width,k[B]||(k[B]=[]),255==n&&255==h&&255==q||1>p.data[F+3]?k[B][x]=null:(n=n.toString(16),h=h.toString(16),q=q.toString(16),n=2>n.length?"0"+n:n,h=2>h.length?"0"+h:h,q=2>q.length?"0"+q:q,k[B][x]="#"+n+h+q);a.forEach(k,function(d){a.forEach(this,function(e){if(0!==z.localeCompare(this)){if(l){t(z,l.width(x));x=l.x();for(C=x+l.width();x<C;x++)for(B=l.y(),
																																																																																																																														p=B+l.height();B<p;B++)k[B][x]=null;l=null}z=this;if(!a.isSet(this))return a.KEYWORDS.CONTINUE;l=new a.Rectangle(e.key,d.key);x=1;for(C=d.key+1;;C++){if(!k[C]||k[C][e.key]!=z){l.height(x);break}x++}x=1}else a.isSet(z)&&x++})});l&&t(z,l.width(x));return this};this.getCurrentTileNumber=function(){if(!this.isTiles())return 0;var a=parseInt(n,10);a>e.length&&(a=0);return e[a]||1};this.getCurrentTilePosition=function(){if(!this.isTiles())return new a.Point;var d=this.getCurrentTileNumber(),e=0;return a.forEach(h,
	function(){return a.forEach(this,function(){if(++e==d)return this})})}},Room:function(c,h,e){var k=null,d=0,l=0,q=null,n=null;this.getName=function(){return k};this.getWidth=function(){return d};this.getHeight=function(){return l};this.view=function(d,e,c,k){if(d===p)return q;q=new a.Rectangle(d,e,c,k);return this};this.viewLinkedElement=function(a){if(a===p)return n;(n=a)&&a.getGame().checkElementsForActivation(!0);return this};this.eventStart=function(){};h!==p&&(k=c,d=h,l=e)},Point:function(c,
																																																																																																																													   h){var e=0,k=0;this.x=function(a){if(a===p)return e;e=parseFloat(a,10);return this};this.y=function(a){if(a===p)return k;k=parseFloat(a,10);return this};this.equals=function(d){return d instanceof a.Point?this.x()==d.x()&&this.y()==d.y():!1};this.copy=function(d){if(d instanceof a.Point)return this.x(d.x()).y(d.y());throw new TypeError("Point.copy() -> given point is not an instance of Point.");};this.add=function(d,c){return d instanceof a.Point?this.x(e+d.x()).y(k+d.y()):this.x(e+(d||0)).y(k+(c||
	0))};this.substract=function(d,c){return d instanceof a.Point?this.x(e-d.x()).y(k-d.y()):this.x(e-(d||0)).y(k-(c||0));throw new TypeError("Point.substract() -> given point is not an instance of Point.");};this.isInRectangle=function(a){var e=this.x(),c=this.y(),k=a.x(),g=a.y(),h=a.width();a=a.height();return e>=k&&e<k+h&&c>=g&&c<g+a};this.getDistanceTo=function(a){return Math.sqrt(Math.pow(e-a.x(),2)+Math.pow(k-a.y(),2))};c!==p&&(c instanceof a.Point?this.copy(c):this.x(c).y(h))},Rectangle:function(c,
																																																																																																																															h,e,k){var d=new a.Point,l=0,q=0;this.position=function(e,c){if(e===p)return d;e instanceof a.Point?d.copy(e):d.x(e).y(c);return this};this.x=function(a){if(a===p)return d.x();d.x(a);return this};this.y=function(a){if(a===p)return d.y();d.y(a);return this};this.width=function(a){if(a===p)return l;l=parseInt(a,10);return this};this.height=function(a){if(a===p)return q;q=parseInt(a,10);return this};this.getCenter=function(){return new a.Point(d.x()+l/2,d.y()+q/2)};this.isCollidedWithRectangle=function(a){var d=
	this.x(),e=this.y(),c=this.width(),k=this.height(),m=a.x(),l=a.y(),h=a.width();a=a.height();return!(m>=d+c||m+h<=d||l>=e+k||l+a<=e)};c!==p&&(c instanceof a.Rectangle?(this.position(c.position()),this.width(c.width()),this.height(c.height())):c instanceof a.Point?(this.position(c),this.width(h),this.height(e)):(this.position(c,h),this.width(e),this.height(k)))},Drawing:{get BLENDING_MODES(){return{NORMAL:1,DIVIDE:2,SCREEN:3,OVERLAY:4,DODGE:5,BURN:6,HARD_LIGHT:7,GRAIN_EXTRACT:8,GRAIN_MERGE:9,AVERAGE:10,
	DIFFERENCES:11,ADDITION:12,SUBSTRACT:13,DARKEN_ONLY:14,LIGHTEN_ONLY:15,MULTIPLY:16}},get CANVAS_FILTER(){return T},get CTX_FILTER(){return ba},Object:function(){var c=100,h=new a.Color("#000"),e="#000",k=0;this.opacity=function(a){if(a===p)return c;c=parseInt(a,10);return this};this.color=function(d,e){if(!d)return h;h=new a.Color(d,e);return this};this.borderColor=function(d,c){if(!d)return e;e=new a.Color(d,c);return this};this.borderSize=function(a){if(a===p)return k;k=a;return this};this.draw=
	function(){throw Error("Class \"Drawing.Object\" shouldn't be directly called! You should use an inherited class from this one. Or maybe the inherited class doesn't overwritte the method draw()?");}},Rectangle:function(c,h){a.Drawing.Object.call(this);var e=c||1,k=h||1;this.width=function(a){if(a===p)return e;e=parseInt(a,10);return this};this.height=function(a){if(a===p)return k;k=parseInt(a,10);return this};this.draw=function(a,c,h){a.fillRect(c.x(),c.y(),e,k);h&&a.strokeRect(h.x(),h.y(),e,k)}},
	Line:function(c,h){a.Drawing.Object.call(this);this.borderSize(1);var e=new a.Point(c),k=new a.Point(h);this.firstPoint=function(a){if(!a)return e;e.copy(a);return this};this.secondPoint=function(a){if(!a)return k;k.copy(a);return this};this.color=function(a,e){return this.borderColor(a,e)};this.draw=function(a,c,h){h&&(c=h.x(),h=h.y(),a.beginPath(),a.moveTo(c+e.x(),h+e.y()),a.lineTo(c+k.x(),h+k.y()),a.stroke())}},Circle:function(c){a.Drawing.Object.call(this);var h=c;this.radius=function(a){if(!a)return h;
		h=a;return this};this.draw=function(a,c,d){a.beginPath();a.arc(c.x(),c.y(),h,0,360,!1);a.closePath();a.fill();d&&a.stroke()}},Shape:function(c){a.Drawing.Object.call(this);var h=c.slice(0);this.points=function(a){if(!a)return h;h=a;return this};this.draw=function(e,c,d){var l=c.x(),p=c.y();e.beginPath();a.forEach(h,function(a){e[0<a.key?"lineTo":"moveTo"](l+this.x(),p+this.y())});e.closePath();e.fill();d&&e.stroke()}},Text:function(c,h,e,k){a.Drawing.Object.call(this);var d=c+""||"",l=h||"20px Calibri",
		q=parseInt(e,10)||0,n=parseInt(k,10)||20;this.text=function(a){if(a===p)return d;d=a+"";return this};this.font=function(a){if(!a)return l;l=a;return this};this.maxWidth=function(a){if(a===p)return q;q=parseInt(a,10);return this};this.lineHeight=function(a){if(a===p)return n;n=parseInt(a,10);return this};this.getLines=function(){var c=d.split("\n"),e=H.createElement("canvas").getContext("2d");e.textBaseline="top";e.font=l;e.lineWidth=this.borderSize();0<q&&a.forEach(c,function(a){var d=e.measureText(this).width,
		m="",k=-1,l="",h="",n=[],p=0;if(d>q){n=this.split(" ");p=n.length;do if(l=h,h+=n[++k]+" ",e.measureText(h).width>q||k==p)m+=l+"\n",h=n[k]+" ";while(k<d);c[a.key]=m}else c[a.key]+="\n"});return c};this.numberOfLines=function(){return this.getLines().length};this.getWidth=function(){var a=H.createElement("canvas").getContext("2d"),c=0;a.textBaseline="top";a.font=l;a.lineWidth=this.borderSize();c=a.measureText(d).width;return q<c&&0<q?e:c};this.getHeight=function(){return this.numberOfLines()*n};this.draw=
		function(d,c,e){var k=e?e.x():0,m=e?e.y():0,h=c.x(),p=c.y();d.font=l;a.forEach(this.getLines(),function(a){e&&d.strokeText(this,k,m+a.key*n+n);d.fillText(this,h,p+a.key*n+n)})}},Sprite:function(c){a.Drawing.Object.call(this);var h=c,e=null;this.sprite=function(a){if(!a)return h;h=a;return this};this.filter=function(a){if(!a)return e;e=a;return this};this.draw=function(c,d){var l=new a.Point(0,0),p=h.getTilesWidth(),n=h.getTilesHeight(),g=0,t=0,w=h.getImage();h.animate();h.isTiles()&&l.copy(h.getCurrentTilePosition());
		g=l.x();t=l.y();c.drawImage(w,g,t,p,n,d.x(),d.y(),p,n);e&&(a.Drawing.CANVAS_FILTER.width=p,a.Drawing.CANVAS_FILTER.height=n,a.Drawing.CTX_FILTER.drawImage(w,g,t,p,n,0,0,p,n),e.draw(c,d))}},Filter:function(c){a.Drawing.Object.call(this);var h=c||1;this.mode=function(a){if(!a)return h;h=a;return this};this.draw=function(c,k){for(var d=a.Drawing.CTX_FILTER.getImageData(0,0,a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height),l=0,p=d.data.length,n=new a.Color(this.color()),g=n.getRGB(),t=function(){switch(h){case a.Drawing.BLENDING_MODES.MULTIPLY:return function(a,
																																																																																																																																																	  d,c){return{red:a*g.red/255,green:d*g.green/255,blue:c*g.blue/255}};case a.Drawing.BLENDING_MODES.DIVIDE:return function(a,d,c){return{red:Math.min(255,256*a/(g.red+1)),green:Math.min(255,256*d/(g.green+1)),blue:Math.min(255,256*c/(g.blue+1))}};case a.Drawing.BLENDING_MODES.SCREEN:return function(a,d,c){return{red:255-(255-g.red)*(255-a)/255,green:255-(255-g.green)*(255-d)/255,blue:255-(255-g.blue)*(255-c)/255}};case a.Drawing.BLENDING_MODES.OVERLAY:return function(a,d,c){return{red:a/255*(a+2*g.red/
	255*(255-a)),green:d/255*(d+2*g.green/255*(255-d)),blue:c/255*(c+2*g.blue/255*(255-c))}};case a.Drawing.BLENDING_MODES.DODGE:return function(a,d,c){return{red:Math.min(255,256*a/(255-g.red+1)),green:Math.min(255,256*d/(255-g.green+1)),blue:Math.min(255,256*c/(255-g.blue+1))}};case a.Drawing.BLENDING_MODES.BURN:return function(a,d,c){return{red:Math.max(0,255-256*(255-a)/(g.red+1)),green:Math.max(0,255-256*(255-d)/(g.green+1)),blue:Math.max(0,255-256*(255-c)/(g.blue+1))}};case a.Drawing.BLENDING_MODES.HARD_LIGHT:return function(a,
																																																																																																																																						 d,c){return{red:128<g.red?255-(255-2*(g.red-128))*(255-a)/256:Math.min(255,2*g.red*a/256),green:128<g.green?255-(255-2*(g.green-128))*(255-d)/256:Math.min(255,2*g.green*d/256),blue:128<g.blue?255-(255-2*(g.blue-128))*(255-c)/256:Math.min(255,2*g.blue*c/256)}};case a.Drawing.BLENDING_MODES.GRAIN_EXTRACT:return function(a,d,c){return{red:Math.min(255,Math.max(0,a-g.red+128)),green:Math.min(255,Math.max(0,d-g.green+128)),blue:Math.min(255,Math.max(0,c-g.blue+128))}};case a.Drawing.BLENDING_MODES.GRAIN_MERGE:return function(a,
																																																																																																																																																																																																																																																																									   d,c){return{red:Math.min(255,Math.max(0,a+g.red-128)),green:Math.min(255,Math.max(0,d+g.green-128)),blue:Math.min(255,Math.max(0,c+g.blue-128))}};case a.Drawing.BLENDING_MODES.AVERAGE:return function(a,d,c){return{red:(a+g.red)/2,green:(d+g.green)/2,blue:(c+g.blue)/2}};case a.Drawing.BLENDING_MODES.DIFFERENCES:return function(a,d,c){return{red:Math.abs(a-g.red),green:Math.abs(d-g.green),blue:Math.abs(c-g.blue)}};case a.Drawing.BLENDING_MODES.ADDITION:return function(a,d,c){return{red:Math.min(255,
		a+g.red),green:Math.min(255,d+g.green),blue:Math.min(255,c+g.blue)}};case a.Drawing.BLENDING_MODES.SUBSTRACT:return function(a,d,c){return{red:Math.max(0,a-g.red),green:Math.max(0,d-g.green),blue:Math.max(0,c-g.blue)}};case a.Drawing.BLENDING_MODES.DARKEN_ONLY:return function(a,d,c){return{red:Math.min(a,g.red),green:Math.min(d,g.green),blue:Math.min(c,g.blue)}};case a.Drawing.BLENDING_MODES.LIGHTEN_ONLY:return function(a,d,c){return{red:Math.max(a,g.red),green:Math.max(d,g.green),blue:Math.max(c,
		g.blue)}};default:return function(){return{red:g.red,green:g.green,blue:g.blue}}}}();l<p;l+=4)0<d.data[l+3]&&(n=t(d.data[l],d.data[l+1],d.data[l+2]),d.data[l]=n.red,d.data[l+1]=n.green,d.data[l+2]=n.blue);a.Drawing.CTX_FILTER.putImageData(d,0,0);c.globalAlpha=this.opacity()/100;c.drawImage(a.Drawing.CANVAS_FILTER,0,0,a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height,k.x(),k.y(),a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height)}}},Color:function(c,h){var e=0,k=0,d=0,l=0,p=0,
	n=0,g=null,t=function(){var a=n/100,c=l/60,h=p/100*(1-Math.abs(2*a-1)),t=h*(1-Math.abs(c%2-1)),a=a-h/2;0<=c&&1>c?(e=h,k=t,d=0):1<=c&&2>c?(e=t,k=h,d=0):2<=c&&3>c?(e=0,k=h,d=t):3<=c&&4>c?(e=0,k=t,d=h):4<=c&&5>c?(e=t,k=0,d=h):5<=c&&6>c?(e=h,k=0,d=t):d=k=e=0;e=Math.round(255*(e+a));k=Math.round(255*(k+a));d=Math.round(255*(d+a));g=null},w=function(){var a=e/255,c=k/255,h=d/255,t=Math.min(a,c,h),w=Math.max(a,c,h),A=w-t,D=0,H=0,x=0;n=(t+w)/2;0===A?p=l=0:(p=.5>n?A/(w+t):A/(2-w-t),D=((w-a)/6+A/2)/A,H=((w-
		c)/6+A/2)/A,x=((w-h)/6+A/2)/A,a==w?l=x-H:c==w?l=1/3+D-x:h==w&&(l=2/3+H-D),0>l?l+=1:1<l&&--l,l=parseInt(Math.round(360*l),10),p=parseInt(Math.round(100*p),10));n=parseInt(Math.round(100*n),10);g=null};this.getHexadecimal=function(){if(!g){var a=e.toString(16),c=k.toString(16),h=d.toString(16);g="#"+((2>a.length?"0"+a:a)+(2>c.length?"0"+c:c)+(2>h.length?"0"+h:h)).toLowerCase()}return g};this.getRGB=function(){return{red:e,green:k,blue:d}};this.getHSL=function(){return{hue:l,saturation:p,lightness:n}};
	this.setRed=function(a,c){var d=e;e=c?e+a:a;e=Math.min(255,Math.max(0,parseInt(e,10)));d!=e&&w();return this};this.setGreen=function(a,c){var d=k;k=c?k+a:a;k=Math.min(255,Math.max(0,parseInt(k,10)));d!=k&&w();return this};this.setBlue=function(a,c){var e=d;d=c?d+a:a;d=Math.min(255,Math.max(0,parseInt(d,10)));e!=d&&w();return this};this.setHue=function(a,c){var d=l;l=c?l+a:a;l=Math.min(359,Math.max(0,parseInt(l,10)));d!=l&&t();return this};this.setSaturation=function(a,c){var d=p;p=c?p+a:a;p=Math.min(100,
		Math.max(0,parseInt(p,10)));d!=p&&t();return this};this.setLightness=function(a,c){var d=n;n=c?n+a:a;n=Math.min(100,Math.max(0,parseInt(n,10)));d!=n&&t();return this};this.equals=function(a){return a?a.getHexadecimal?this.getHexadecimal()==a.getHexadecimal():!1:!1};if(c instanceof Array)h?(l=c[0],p=c[1],n=c[2],t()):(e=c[0],k=c[1],d=c[2],w());else if(c instanceof a.Color)e=c.getRGB(),k=e.green,d=e.blue,e=e.red,l=c.getHSL(),p=l.saturation,n=l.lightness,l=l.hue;else{c=c.toUpperCase();if(a.Color.NAMES[c])c=
		a.Color.NAMES[c];else if("#"!=c.charAt(0))throw Error('new Color() -> color "'+c+'" is not a valid color.');c=c.substr(1).toLowerCase();3==c.length?(e=parseInt(c.charAt(0)+c.charAt(0),16),k=parseInt(c.charAt(1)+c.charAt(1),16),d=parseInt(c.charAt(2)+c.charAt(2),16)):(e=parseInt(c.charAt(0)+c.charAt(1),16),k=parseInt(c.charAt(2)+c.charAt(3),16),d=parseInt(c.charAt(4)+c.charAt(5),16));w()}}};Object.defineProperty(a.Color,"NAMES",{get:function(){return{ALICEBLUE:"#f0f8ff",ANTIQUEWHITE:"#faebd7",AQUA:"#0ff",
	AQUAMARINE:"#7fffd4",AZURE:"#f0ffff",BEIGE:"#f5f5dc",BISQUE:"#ffe4c4",BLACK:"#000",BLANCHEDALMOND:"#ffebcd",BLUE:"#00f",BLUEVIOLET:"#8a2be2",BROWN:"#a52a2a",BURLYWOOD:"#deb887",CADETBLUE:"#5f9ea0",CHARTREUSE:"#7fff00",CHOCOLATE:"#d2691e",CORAL:"#ff7f50",CORNFLOWERBLUE:"#6495ed",CORNSILK:"#fff8dc",CRIMSON:"#dc143c",CYAN:"#0ff",DARKBLUE:"#00008b",DARKCYAN:"#008b8b",DARKGOLDENROD:"#b8860b",DARKGRAY:"#a9a9a9",DARKGREY:"#a9a9a9",DARKGREEN:"#006400",DARKKHAKI:"#bdb76b",DARKMAGENTA:"#8b008b",DARKOLIVEGREEN:"#556b2f",
	DARKORANGE:"#ff8c00",DARKORCHID:"#9932cc",DARKRED:"#8b0000",DARKSALMON:"#e9967a",DARKSEAGREEN:"#8fbc8f",DARKSLATEBLUE:"#483d8b",DARKSLATEGRAY:"#2f4f4f",DARKSLATEGREY:"#2f4f4f",DARKTURQUOISE:"#00ced1",DARKVIOLET:"#9400d3",DEEPPINK:"#ff1493",DEEPSKYBLUE:"#00bfff",DIMGRAY:"#696969",DIMGREY:"#696969",DODGERBLUE:"#1e90ff",FIREBRICK:"#b22222",FLORALWHITE:"#fffaf0",FORESTGREEN:"#228b22",FUCHSIA:"#f0f",GAINSBORO:"#dcdcdc",GHOSTWHITE:"#f8f8ff",GOLD:"#ffd700",GOLDENROD:"#daa520",GRAY:"#808080",GREY:"#808080",
	GREEN:"#008000",GREENYELLOW:"#adff2f",HONEYDEW:"#f0fff0",HOTPINK:"#ff69b4",INDIANRED:"#cd5c5c",INDIGO:"#4b0082",IVORY:"#fffff0",KHAKI:"#f0e68c",LAVENDER:"#e6e6fa",LAVENDERBLUSH:"#fff0f5",LAWNGREEN:"#7cfc00",LEMONCHIFFON:"#fffacd",LIGHTBLUE:"#add8e6",LIGHTCORAL:"#f08080",LIGHTCYAN:"#e0ffff",LIGHTGOLDENRODYELLOW:"#fafad2",LIGHTGRAY:"#d3d3d3",LIGHTGREY:"#d3d3d3",LIGHTGREEN:"#90ee90",LIGHTPINK:"#ffb6c1",LIGHTSALMON:"#ffa07a",LIGHTSEAGREEN:"#20b2aa",LIGHTSKYBLUE:"#87cefa",LIGHTSLATEGRAY:"#778899",LIGHTSLATEGREY:"#778899",
	LIGHTSTEELBLUE:"#b0c4de",LIGHTYELLOW:"#ffffe0",LIME:"#0f0",LIMEGREEN:"#32cd32",LINEN:"#faf0e6",MAGENTA:"#f0f",MAROON:"#800000",MEDIUMAQUAMARINE:"#66cdaa",MEDIUMBLUE:"#0000cd",MEDIUMORCHID:"#ba55d3",MEDIUMPURPLE:"#9370db",MEDIUMSEAGREEN:"#3cb371",MEDIUMSLATEBLUE:"#7b68ee",MEDIUMSPRINGGREEN:"#00fa9a",MEDIUMTURQUOISE:"#48d1cc",MEDIUMVIOLETRED:"#c71585",MIDNIGHTBLUE:"#191970",MINTCREAM:"#f5fffa",MISTYROSE:"#ffe4e1",MOCCASIN:"#ffe4b5",NAVAJOWHITE:"#ffdead",NAVY:"#000080",OLDLACE:"#fdf5e6",OLIVE:"#808000",
	OLIVEDRAB:"#6b8e23",ORANGE:"#ffA500",ORANGERED:"#ff4500",ORCHID:"#da70d6",PALEGOLDENROD:"#eee8aa",PALEGREEN:"#98fb98",PALETURQUOISE:"#afeeee",PALEVIOLETRED:"#db7093",PAPAYAWHIP:"#ffefd5",PEACHPUFF:"#ffdab9",PERU:"#cd853f",PINK:"#ffc0cb",PLUM:"#dda0dd",POWDERBLUE:"#b0e0e6",PURPLE:"#800080",RED:"#f00",ROSYBROWN:"#bc8f8f",ROYALBLUE:"#4169e1",SADDLEBROWN:"#8b4513",SALMON:"#fa8072",SANDYBROWN:"#f4a460",SEAGREEN:"#2e8b57",SEASHELL:"#fff5ee",SIENNA:"#a0522d",SILVER:"#c0c0c0",SKYBLUE:"#87ceeb",SLATEBLUE:"#6a5acd",
	SLATEGRAY:"#708090",SLATEGREY:"#708090",SNOW:"#fffafa",SPRINGGREEN:"#00ff7f",STEELBLUE:"#4682b4",TAN:"#d2b48c",TEAL:"#008080",THISTLE:"#d8bfd8",TOMATO:"#ff6347",TURQUOISE:"#40e0D0",VIOLET:"#ee82ee",WHEAT:"#f5deb3",WHITE:"#fff",WHITESMOKE:"#f5f5f5",YELLOW:"#ff0",YELLOWGREEN:"#9acd32"}}});A.JSGlib=a})(window,document);