/*!
 * JSGlib v3.0 (minified), JavaScript Library
 * http://jsglib.no-ip.org/
 *
 * Copyright 2011-2013, Adrien Guéret
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * 
 * Date: 20/04/2013
 */
(function(B,E,k){var a={},X=0,ga=B.requestAnimationFrame||B.webkitRequestAnimationFrame||B.mozRequestAnimationFrame||B.oRequestAnimationFrame||B.msRequestAnimationFrame||function(a){var h=(new Date).getTime(),d=Math.max(0,16-(h-X));B.setTimeout(function(){a(h+d)},d);X=h+d},V={},S=[],P={WALL:1,SLOPE:2},Y=E.createElement("canvas"),ha=Y.getContext("2d"),ia=2,J=navigator.userLanguage?navigator.userLanguage:navigator.language,Z=J.indexOf("-"),y={STAND:10,STAND_LEFT:11,STAND_RIGHT:12,STAND_UP:13,STAND_DOWN:14,
STAND_UP_LEFT:15,STAND_UP_RIGHT:16,STAND_DOWN_LEFT:17,STAND_DOWN_RIGHT:18,MOVE:20,MOVE_LEFT:21,MOVE_RIGHT:22,MOVE_UP:23,MOVE_DOWN:24,MOVE_UP_LEFT:25,MOVE_UP_RIGHT:26,MOVE_DOWN_LEFT:27,MOVE_DOWN_RIGHT:28,HURT:30,HURT_LEFT:31,HURT_RIGHT:32,HURT_UP:33,HURT_DOWN:34,HURT_UP_LEFT:35,HURT_UP_RIGHT:36,HURT_DOWN_LEFT:37,HURT_DOWN_RIGHT:38,DEATH:40,DEATH_LEFT:41,DEATH_RIGHT:42,DEATH_UP:43,DEATH_DOWN:44,DEATH_UP_LEFT:45,DEATH_UP_RIGHT:46,DEATH_DOWN_LEFT:47,DEATH_DOWN_RIGHT:48,SLIP:50,SLIP_LEFT:51,SLIP_RIGHT:52,
SLIP_UP:53,SLIP_DOWN:54,SLIP_UP_LEFT:55,SLIP_UP_RIGHT:56,SLIP_DOWN_LEFT:57,SLIP_DOWN_RIGHT:58},J=-1<Z?J.substr(0,Z):J,a={get TILES_TYPES(){return P},get USER_LANG(){return J},get KEYWORDS(){return{BREAK:"JSGLIB_BREAK",CONTINUE:"JSGLIB_CONTINUE",NULL:"JSGLIB_NULL",UNDEFINED:"JSGLIB_UNDEFINED",REPEAT:"JSGLIB_REPEAT",REVERSE:"JSGLIB_REVERSE"}},get BACKGROUND(){return{NO_REPEAT:0,REPEAT_X:1,REPEAT_Y:2,REPEAT:3}},get KEY(){return{TAB:9,ENTER:13,SHIFT:16,CTRL:17,CONTROL:17,ALT:18,CAPS_LOCK:20,SPACE:32,
LEFT:37,UP:38,RIGHT:39,DOWN:40,A:65,B:66,C:67,D:68,E:69,F:70,G:71,H:72,I:73,J:74,K:75,L:76,M:77,N:78,O:79,P:80,Q:81,R:82,S:83,T:84,U:85,V:86,W:87,X:88,Y:89,Z:90}},get STATE(){return y},addStateConstant:function(c){var h=10,d=0;c=c.toUpperCase();if(y[c])throw new ReferenceError('JSGlib.addStateConstant() => constant "'+c+'" already exists.');a.forEach(y,function(){this>h&&0===this%10&&(h=this)});d=h+=10;y[c]=h;c+="_";y[c+"LEFT"]=++h;y[c+"RIGHT"]=++h;y[c+"UP"]=++h;y[c+"DOWN"]=++h;y[c+"UP_LEFT"]=++h;
y[c+"UP_RIGHT"]=++h;y[c+"DOWN_LEFT"]=++h;y[c+"DOWN_RIGHT"]=++h;a.Element.prototype["isState"+c]=function(){var a=this.state();return a>=d&&a<=h};return a},isKeyPressed:function(c){c=c.valueOf();return a.forEach(S,function(){if(this.valueOf()==c)return!0})||!1},forceKeyUp:function(c,h){var d=a.removeFromArray(c,S);d&&!h&&a.forEach(V,function(){this.emitEvent("eventKeyUp",c)});return d},isNull:function(c){return null===c||c==a.KEYWORDS.NULL},isUndefined:function(c){return c===k||c==a.KEYWORDS.UNDEFINED},
isSet:function(c){return!a.isNull(c)&&!a.isUndefined(c)},getVectorDirection:function(a,h){if(0===a||0===h)return 0===a?0<h?270:0>h?90:0:0===h?0>a?180:360:0;var d=Math.round(180*Math.abs(Math.atan(h/a))/Math.PI);return 0>a&&0>h?180-d:0<a&&0<h?360-d:0>a?180+d:d},removeFromArray:function(c,h,d){d=d||function(a,e){return a==e};return a.forEach(h,function(a){if(d(c,this))return h.splice(a.key,1),!0})||!1},uniqueArray:function(c,h){var d={},j=[];a.forEach(c,function(){d[h?this.getId():this]=this});a.forEach(d,
function(){j.push(this)});return j},ajax:function(c){var h=B.XMLHttpRequest?new XMLHttpRequest:new B.ActiveXObject("Microsoft.XMLHTTP"),d="",j=!0,e=function(d,c,j){d=j===k?d:j+"["+d+"]";if("object"==typeof c.valueOf()){var f="";a.forEach(c,function(a){f+=e(a.key,this,d)});return f}return d+"="+c+"&"};a.forEach({url:"./",async:!0,type:"POST",dataType:"TEXT",data:{},onAjaxAborted:function(){},onError:function(){},onSuccess:function(){}},function(a){c[a.key]===k&&(c[a.key]=this)});j="POST"==c.type;c.dataType=
c.dataType.toUpperCase();if(h)a.forEach(c.data,function(a){d+=e(a.key,this)}),d=d.substr(0,d.length-1),h.onreadystatechange=function(){if(4==h.readyState)if(200==h.status||304==h.status)c.onSuccess("JSON"==c.dataType?JSON.parse(h.responseText):"XML"==c.dataType?h.responseXML:h.responseText);else c.onError(h.statusText)},h.open(c.type,c.url+(j?"":"?"+d),c.async),j&&h.setRequestHeader("Content-type","application/x-www-form-urlencoded"),h.send(j?d:null);else c.onAjaxAborted();return this},random:function(a,
h){var d=0;a>h&&(d=h,h=a,a=d);return Math.floor((1+h-a)*Math.random())+a},forEach:function(c,h,d){var j="",e=0,g=null,q=function(e,d){var g=c[e];d.key=e;g===k?g=a.KEYWORDS.UNDEFINED:null===g&&(g=a.KEYWORDS.NULL);return h.call(g.valueOf(),d)};d={values:d};if(c instanceof Array||c instanceof B.NodeList){e=c.length;for(j=0;j<e;j++)if(g=q(j,d),g!==k)if(g==a.KEYWORDS.BREAK)break;else if(g!=a.KEYWORDS.CONTINUE)return g}else for(j in c)if(c.hasOwnProperty(j)&&(g=q(j,d),g!==k))if(g==a.KEYWORDS.BREAK)break;
else return g},Game:function(c,h){if(!c)throw new ReferenceError("new JSGlib.Game(idContainer) -> please provide a paramater.");if(V[c])throw Error('Container with id "'+c+'" already contains a game.');var d=h?parseInt(h,10):16,j={},e=this,g=null,q=null,n=null,f={},s={},r=[],t=[],l=!1,u=[],K={},Q=!1,R=!1,H=new a.Point,L=[],w=[],z=[],x={},D=[],A=[],C={},m=60,ja=0,N=0,T=[],W="en",O={},I=0,$=function(){setTimeout(function(){y(!1,function(){var b=this;a.forEach(b.elements,function(){if(e.isElementActive(this)){var v=
this.sprite(),p=null,d=null,c=0,m=p=0,f=0,g=null;v&&(p=new a.Point(0,0),d=v.getImage(),m=this.width(),f=this.height(),g=this.filter(),v.isTiles()&&p.copy(v.getCurrentTilePosition()),c=p.x(),p=p.y(),b.ctx.globalAlpha=this.opacity()/100,b.ctx.drawImage(d,c,p,m,this.height(),parseInt(this.x(),10),parseInt(this.y(),10),m,f),g&&(a.Drawing.CANVAS_FILTER.width=m,a.Drawing.CANVAS_FILTER.height=f,a.Drawing.CTX_FILTER.drawImage(d,c,p,m,f,0,0,m,f),g.draw(b.ctx,this.position())),b.ctx.globalAlpha=1)}})});a.forEach(T,
function(){var b=this.layer,v=this.object.borderSize(),p=new a.Point(parseInt(this.position.x(),10),parseInt(this.position.y(),10)),d=null;b.ctx.globalAlpha=this.object.opacity()/100;b.ctx.fillStyle=this.object.color().getHexadecimal();b.ctx.globalCompositeOperation=this.eraseMode?"destination-out":"source-over";0<v&&(b.ctx.strokeStyle=this.object.borderColor().getHexadecimal(),b.ctx.lineWidth=v,d=new a.Point(p),0<b.ctx.lineWidth%2&&d.substract(0.5,0.5));this.object.draw(b.ctx,p,d)});ga($)},1E3/m)},
y=function(b,v){var p=n?n.view():null,d=null,e=function(){};null!==p&&(d=p.position(),e=function(){this.canvas.style.left="-"+d.x()*this.hspeed+"px";this.canvas.style.top="-"+d.y()*this.vspeed+"px"});a.forEach(A,function(){e.call(this);if(b||this.needRefresh)this.canvas.width=g.getAttribute("data-jsglib-room-width"),this.canvas.height=g.getAttribute("data-jsglib-room-height"),this.needRefresh=!1,v&&v.call(this);var p=this;0<this.animatedTiles.length&&a.forEach(this.animatedTiles,function(){var b=
0,a=0;null!==this.sprite.animate()&&(b=this.position.x(),a=this.position.y(),p.tiles[b][a]=this.sprite.getCurrentTileNumber(),p.drawTile(b,a))})})},aa=function(){a.forEach(D,function(){var b=function(b,a){return b.equals(a)},v=G(this.getLayer());a.removeFromArray(this,v.elements,b);a.removeFromArray(this,L,b);a.removeFromArray(this,w,b);z[this.getId()]=null;v.needRefresh=!0});D.length=0},F=function(b,a,p){if(b[a])return p instanceof Array||(p=[p]),b[a].apply(b,p)},M=function(b,v){var p=!0;a.forEach(w,
function(){!1===F(this,b,v)&&(p=!1)});if(!1===p)return!1},fa=function(){T.length=0;N++;J();F(e,"eventStartStep",[N]);a.forEach(L,function(){if(e.isElementActive(this)){var b=this,v=b.getLayer(),v=G(v),p=b.sprite(),d=null,m=p?p.usedTiles().toString():"";b.prevPosition(b.position()).spriteModified(!1);F(b,"eventStartStep",N);p&&(d=p.animate(),null!==d&&d&&F(b,"eventAnimationEnd"));a:{var c=b.hspeed(),f=b.vspeed()+b.gravity(),g=parseInt(b.prevPosition().x(),10),t=parseInt(b.prevPosition().y(),10),l=
!1,j=!1,h=[],l=b.spriteModified(),r=b.sprite(),r=(b.maskColorForSolidCollisions()?!0:!1)&&(r?0<r.getCurrentMasks().length:!1),u=!1,q;if(l||0!==c||0!==f)if(b.vspeed(f),b.x(b.x()+c),b.y(b.y()+f),q=!b.prevPosition().equals(b.position()),b.checkCollisions()&&(l||q)){l=ba(b,h);j=ca(b,h);if((l||j)&&b.stopOnSolids()){r?a.forEach(h,function(){if(this.concernElement&&("eventCollision"==this.eventName?this.data[1].thisMasks:this.data[1])[b.maskColorForSolidCollisions().getHexadecimal()])return u=!0,a.KEYWORDS.BREAK}):
u=!0;if(!u)break a;b.position().x(g).y(t);l&&da(b,ba);j&&da(b,ca)}a.forEach(h,function(){F(this.target,this.eventName,this.data)})}if(q||Q)b.equals(n.viewLinkedElement())?e.checkElementsForActivation():ea(b),e.isElementInsideView(b)?F(b,"eventInsideView"):F(b,"eventOutsideView")}F(b,"eventStep",N);b.checkMoveToPointCallback();a.forEach(b.getAlarms(),function(a){b.setAlarm(a.key,-1,!0)&&F(b,"eventAlarm"+a.key)});F(b,"eventEndStep",N);p&&(0<p.getCurrentMasks().length&&p.usedTiles().toString()!=m)&&
b.spriteModified(!0);if(v.containsElements&&!v.needRefresh&&(function(){return null!==d||b.spriteModified()||!b.prevPosition().equals(b.position())}||function(){return!0})())v.needRefresh=!0}});F(e,"eventEndStep",[N]);aa();x={};setTimeout(fa,1E3/m)},J=function(){var b=n.view(),v,p,d;if(null===b)return!1;p=new a.Point(b.position());v=n.viewLinkedElement();if(null===v)return!1;d=v.x()+v.width()/2-b.width()/2;v=v.y()+v.height()/2-b.height()/2;d=Math.max(d,0);v=Math.max(v,0);d=d+b.width()>n.getWidth()?
n.getWidth()-b.width():d;v=v+b.height()>n.getHeight()?n.getHeight()-b.height():v;b.position(d,v);Q=!p.equals(b.position());return!0},da=function(b,a){for(var p=0,d=0,d=b.hspeed(),e=b.vspeed()+b.gravity(),m=0<d?1:-1,c=0<e?1:-1,d=Math.abs(d);p<d;p++)if(b.x(b.x()+m),a(b,null,!0)){b.x(b.x()-m);break}p=0;for(d=Math.abs(e);p<d;p++)if(b.y(b.y()+c),a(b,null,!0)){b.y(b.y()-c);break}},ba=function(b,v,p){var m=!1,c=b.sprite(),f=c?c.getCurrentMasks():[],c=c?c.getCurrentTilePosition():new a.Point,g=c.x(),l=c.y(),
t=0<f.length,j={},c=b.getRectangleRepresentation(),h=c.x(),r=c.y(),c=e.isRectangleCollidedWithTiles(c);if(!c)return!1;a.forEach(c,function(b){var v=this.type==P.WALL,e,c,n=function(){return v?(m=!0,a.KEYWORDS[p?"BREAK":"CONTINUE"]):a.KEYWORDS.CONTINUE};if(t)e=new a.Rectangle(this.position,d,d),c=this,a.forEach(f,function(){var b=new a.Rectangle(this.rectangle);b.position().substract(g,l).add(h,r);if(b.isCollidedWithRectangle(e,!0)){if(n()==a.KEYWORDS.BREAK)return a.KEYWORDS.BREAK;p||(b=c.layer+"_"+
c.position.x()+"_"+c.position.y(),j[b]||(j[b]={tile:c,masks:{}}),j[b].masks[this.color]=!0)}});else if(p||(j[b.key]={tile:this,masks:{}}),n()==a.KEYWORDS.BREAK)return a.KEYWORDS.BREAK});p||a.forEach(j,function(){v.push({target:b,concernElement:!0,eventName:"eventTileCollision",data:[this.tile,this.masks]})});return m},ca=function(b,d,p){var c=!1,e=b.sprite(),e=e?e.getCurrentMasks():[],m=b.getId(),f=0<e.length;x[m]||(x[m]={});a.forEach(w,function(){var e=this.getId(),g,l;if(m!=e&&this.checkCollisions()&&
(!x[m][e]||p)){x[m][e]=!0;x[e]||(x[e]={});x[e][m]=!0;e=b.isCollidedWithElement(this);if(!e)return a.KEYWORDS.CONTINUE;g=(g=this.sprite())?g.getCurrentMasks():[];l=0<g.length;g=this.solid();if(!f&&!l||f&&l&&e.thisHasMasksCollided&&e.otherHasMasksCollided||f&&e.thisHasMasksCollided||l&&e.otherHasMasksCollided)if(p||(d.push({target:this,eventName:"eventCollision",data:[b,{thisMasks:e.otherMasks,otherMasks:e.thisMasks,thisHasMasksCollided:e.otherHasMasksCollided,otherHasMasksCollided:e.thisHasMasksCollided}]}),
d.push({target:b,concernElement:!0,eventName:"eventCollision",data:[this,e]})),g&&(c=!0,p))return a.KEYWORDS.BREAK}});return c},ea=function(b){e.isElementInsideRoom(b)?F(b,"eventMoveInsideRoom"):F(b,"eventMoveOutsideRoom");if(!b.alwaysActive()){var a=e.isElementActive(b),d=e.isElementInsideView(b);!a&&d?e.activateElement(b):a&&!d&&e.deactivateElement(b)}},G=function(b){var d=a.forEach(A,function(){if(this.name==b)return this});if(d)return d;throw new ReferenceError('Layer naming "'+b+'" is not defined for this game.');
},U=function(){if(!n||!this.backgroundAlias)return!1;var b=e.getImage(this.backgroundAlias),d=b?b.width:0,p=b?b.height:0,c=this.backgroundPosition.x(),m=this.backgroundPosition.y(),f=0,l=0;if(!b)return!1;this.canvas.width=g.getAttribute("data-jsglib-room-width")*Math.max(1,this.hspeed);this.canvas.height=g.getAttribute("data-jsglib-room-height")*Math.max(1,this.vspeed);if(this.backgroundRepeat==a.BACKGROUND.NO_REPEAT)this.ctx.drawImage(b,0,0,d,p,c,m,d,p);else if(this.backgroundRepeat==a.BACKGROUND.REPEAT_X)for(;f<
this.canvas.width;f+=d)this.ctx.drawImage(b,0,0,d,p,f,m,d,p);else if(this.backgroundRepeat==a.BACKGROUND.REPEAT_Y)for(;l<this.canvas.height;l+=p)this.ctx.drawImage(b,0,0,d,p,c,l,d,p);else for(f=0;f<this.canvas.width;f+=d)for(l=0;l<this.canvas.height;l+=p)this.ctx.drawImage(b,0,0,d,p,f,l,d,p)};this.addClass=function(b){if(!b.name)throw new ReferenceError("Class definition must have a name.");if(C[b.name])throw Error('Class "'+b.name+'" is already defined for this game.');var d=null,p=b.name,c={},m=
["Element"],f=function(b,e){a.forEach(b,function(b){e?d[b.key]=this:c[b.key]=this})};b.parent=b.parent===k?[]:b.parent;"string"==typeof b.parent&&(b.parent=[b.parent]);d=function(b,d){a.Element.call(this,b.x(),b.y(),d,e)};a.forEach(b.parent,function(){if(!C[this])throw Error('Game.addClass() -> Parent "'+this+'" for class "'+p+'" is not defined in this game.');m=m.concat(C[this]._types);f(C[this].prototype)});m=m.concat(b.parent);m.push(p);m=a.uniqueArray(m);Object.defineProperty(c,"_types",{get:function(){return m}});
Object.defineProperty(d,"_types",{get:function(){return m}});d["abstract"]=b["abstract"]||!1;b["static"]&&(f(b["static"],!0),delete b["static"]);delete b.parent;delete b["abstract"];delete b.name;f(a.Element.prototype);f(b);d.prototype=c;C[p]=d;return this};this.callParent=function(b,a,d,e){if(e){if(!b.instanceOf(e))throw new TypeError('Game.callParent() -> instance of types "['+b._types+']" is not an instance of "'+e+'".');}else e=b._types[b._types.length-2];if(C[e].prototype[a])return d=d===k?[]:
d,d instanceof Array||(d=[d]),C[e].prototype[a].apply(b,d);throw new ReferenceError('Game.callParent() -> class "'+e+'" has no methods named "'+a+'".');};this.callStatic=function(b,a,d){if(C[b][a])return d=d===k?[]:d,d instanceof Array||(d=[d]),C[b][a].apply(null,d);throw new ReferenceError('Game.callStatic() -> class "'+b+'" has no methods named "'+a+'".');};this.checkElementsForActivation=function(b){b&&J();a.forEach(L,function(){ea(this)});return this};this.orderElementsOnLayer=function(b){G(b).elements.sort(function(b,
a){return b.zIndex()-a.zIndex()});return this};this.updateMaxZIndex=function(b){b>I&&(I=b);return this};this.putElementToFirstPlan=function(b){b.zIndex()<I&&b.zIndex(++I);return this};this.emitEvent=function(b,a){M(b,a);return this};this.instanceCreate=function(b,d,e,c){var m=null,f=m=null,f=0;b instanceof a.Point?(m=b,e=d):m=new a.Point(b,d);if(!C[e])throw new ReferenceError('Game.instanceCreate() -> Class "'+e+'" is not defined in this game.');if(C[e]["abstract"])throw Error('Game.instanceCreate() -> Class "'+
e+"\" is abstract and can't be instancied.");c=c||"main";f=G(c);if(!f.containsElements)throw Error('Layer "'+c+'" is set to forbid elements inside it. Consider using tiles instead.');m=new C[e](m,c);L.push(m);w.push(m);z[m.getId()]=!0;f.elements.push(m);f.needRefresh=!0;f=m.zIndex();f>I&&(I=f);F(m,"eventCreate");return m};this.instanceDestroy=function(b,a){a||F(b,"eventDestroy");D.push(b);return this};this.isElementInsideView=function(b){var a=n.view();return!a?!0:b.getRectangleRepresentation().isCollidedWithRectangle(a)};
this.isElementInsideRoom=function(b){return b.getRectangleRepresentation().isCollidedWithRectangle(new a.Rectangle(0,0,n.getWidth(),n.getHeight()))};this.isElementActive=function(b){return z[b.getId()]};this.activateElement=function(b){this.isElementActive(b)||(w.push(b),z[b.getId()]=!0);return this};this.deactivateElement=function(b){this.isElementActive(b)&&(a.removeFromArray(b,w,function(b,a){return b.equals(a)}),z[b.getId()]=!1);return this};this.getTilesSize=function(){return d};this.load=function(b,
c,m){c=c===k?!0:c;b=b||{};b.images=b.images||{};b.sounds=b.sounds||{};b.tiles=b.tiles||[];b.rooms=b.rooms||[];var l=b.tiles.length+b.rooms.length,t=0,h=function(){var b=parseInt(100*t/l,10),a=G("main").ctx;g.setAttribute("data-jsglib-room-width",500);g.setAttribute("data-jsglib-room-height",30);g.style.width="500px";g.style.height="30px";y(!0);a.fillStyle="#ff0000";a.rect(0,0,500*b/100,30);a.fill();a.fillStyle="#000";a.font="bold 20px Calibri";a.fillText(b+"%",250,20)},r=function(){c&&h();m&&t==l&&
setTimeout(function(){m.call(e)},500)};a.forEach(b.images,function(){l++});a.forEach(b.sounds,function(){l++});0<l?(c&&h(0,l),a.forEach(b.images,function(b){var a=new Image;a.src=this;f[b.key]=a;a.onload=function(){t++;r()}}),a.forEach(b.sounds,function(b){var d=E.createElement("audio");d.preload="auto";g.appendChild(d);a.forEach(this,function(){var b=E.createElement("source"),a="";switch(this.substring(this.lastIndexOf(".")+1)){case "mp3":a="audio/mpeg";break;case "wav":a="audio/wav";break;case "ogg":a=
"audio/ogg"}0<d.canPlayType(a).length&&(b.src=this,d.appendChild(b))});s[b.key]={elem:d,volume:1,onEnd:null,loop:!0};t++;r()}),a.forEach(b.tiles,function(){a.ajax({url:this,async:!1,dataType:"JSON",onError:function(){throw Error('An Ajax error occurs while loading tiles "'+this+'".');},onSuccess:function(b){a.forEach(b,function(b){var c=e.getImage(this.image),m=new a.Sprite(c),f=this,p=function(){m.makeTiles(d,d,f.separation);a.forEach(f.slopes,function(b){var a=this["function"][0],d=this["function"][1];
f.slopes[b.key]["function"]=function(b){return a*b+d}});j[b.key]={sprite:m,animations:f.animations,slopes:f.slopes,separation:f.separation,types:{}};a.forEach(f.types,function(d){var e=d.key;P[e]||(P[e]=++ia);a.forEach(this,function(){j[b.key].types[this]=P[e]})});t++;r()};c.complete?p():c.addEventListener("load",p)})}})}),a.forEach(b.rooms,function(){a.ajax({url:this,async:!1,dataType:"JSON",onError:function(){throw Error('An Ajax error occurs while loading level "'+this+'".');},onSuccess:function(b){var d=
new a.Room(b.name,b.width,b.height);0<b.view_w&&0<b.view_h&&d.view(b.view_x,b.view_y,b.view_w,b.view_h);e.addRooms(d);K[b.name]={elements:b.elements,tiles:b.tiles};t++;r()}})})):m&&m();return this};this.getImage=function(b){return f[b]||null};this.soundIsPlaying=function(b){return b?a.forEach(r,function(){if(this==b)return!0})||!1:0<r.length};this.playSound=function(b,d,c){var m=s[b],f=null;if(m&&m.elem)f=m.elem,this.soundIsPlaying(b)?f.currentTime=0:(r.push(b),s[b].onEnd=c,s[b].loop=d,a.removeFromArray(b,
t)),l&&(f.volume=0),f.play(),f.addEventListener("ended",function ka(){f.removeEventListener("ended",ka,!1);a.removeFromArray(b,r);c&&c.apply(e);d&&(f.currentTime=0,e.playSound(b,!0,c))},!1);else throw new ReferenceError('Game.playSound() -> Sound "'+b+'" is not defined in this game.');return this};this.stopSound=function(b,d,c){var m=s[b],f=null;if(m&&m.elem)f=m.elem,this.soundIsPlaying(b)&&(f.pause(),d?t.push(b):f.currentTime=0,a.removeFromArray(b,r),c&&f.onended&&f.onended.apply(e));else throw new ReferenceError('Game.stopSound() -> Sound "'+
b+'" is not defined in this game.');return this};this.stopAllSounds=function(b,a){for(;0<r.length;)this.stopSound(r[0],b,a);return this};this.replayPausedSounds=function(){for(;0<t.length;){var b=t[0];this.playSound(b,s[b].loop,s[b].onEnd)}return this};this.setSoundVolume=function(b,a){if(!l){var d=s[b];if(d)d.elem.volume=(Math.min(100,Math.max(0,a))/100).toFixed(1);else throw new ReferenceError('Game.setSoundVolume() -> Sound "'+b+'" is not defined in this game.');}return this};this.muteSounds=function(b){if(b===
k)return l;(l=!!b)?a.forEach(s,function(){this.volume=this.elem.volume;this.elem.volume=0}):a.forEach(s,function(){this.elem.volume=this.volume});return this};this.toggleMuteSounds=function(){this.muteSounds(!l);return this};this.defaultLang=function(b){if(!b)return W;W=b;return this};this.defineTranslation=function(b){a.forEach(b,function(b){O[b.key]||(O[b.key]={});a.forEach(this,function(a){O[b.key][a.key]=this})});return this};this.getTranslation=function(b,d,e){if(O[b]){e=e||a.USER_LANG;var c=
O[b][e];c||(c=O[b][W]);return c?(d&&a.forEach(d,function(b){c=c.replace(RegExp("%"+b.key,"g"),this)}),c):"["+b+"]["+e+"]"}throw new ReferenceError('Game.getTranslation() -> Text "'+b+'" is not defined in this game.');};this.isTileAnimated=function(b,d){var e=j[b],c=!1;if(!e)throw new ReferenceError('Game.isTileAnimated(): there is no tiles with name "'+b+'"');c=a.forEach(e.animations,function(b){if(a.forEach(this.tiles,function(){if(d.valueOf()==this)return!0}))return b.key});return c===k?!1:c};this.isTileSlope=
function(b,d){var e=j[b],c=!1;if(!e)throw new ReferenceError('Game.isTileSlope() -> there is no tiles with name "'+b+'"');a.forEach(e.slopes,function(){if(a.forEach(this.tiles,function(){if(d.valueOf()==this)return!0}))return c=this["function"],a.KEYWORDS.BREAK});return c};this.createLayer=function(b,e){if(!b)throw new ReferenceError("Game.createLayer() -> name of new layer undefined.");var c=E.createElement("canvas"),m=c.getContext("2d"),f=ja++;c.id="jsglib-layer-"+b;c.style.position="absolute";
c.style.zIndex=f;c.style.left=0;c.style.top=0;c.width=0;c.height=0;m.textBaseline="top";g.appendChild(c);A.push({name:b,canvas:c,ctx:m,elements:[],tileName:"",tiles:[],animatedTiles:[],spriteTile:null,needRefresh:!0,hspeed:1,vspeed:1,containsElements:e||!1,backgroundAlias:null,backgroundRepeat:a.BACKGROUND.REPEAT,backgroundPosition:new a.Point,drawTile:function(b,c){var e=this.tiles[b][c],m=new a.Point(0,0),f=c*d,l=b*d;0<e&&(this.spriteTile.usedTiles([e]),m.copy(this.spriteTile.getCurrentTilePosition()),
this.ctx.clearRect(f,l,d,d),this.ctx.drawImage(this.spriteTile.getImage(),m.x(),m.y(),d,d,f,l,d,d))}});return this};this.getLayers=function(){var b=[];a.forEach(A,function(){b.push(this.name)});return b};this.isRectangleCollidedWithTiles=function(b){var c=[],e=b.x(),m=b.y(),f=b.width();b=b.height();var l,g,t=Math.floor(e/d),r=Math.floor(m/d),h=Math.floor((e+f-1)/d),n=Math.floor((m+b-1)/d);a.forEach(A,function(){if(0<this.tiles.length){l=t;for(;l<=h;l++)for(g=r;g<=n;g++)if(this.tiles[g]&&this.tiles[g][l]){var b=
j[this.tileName].types[this.tiles[g][l]],e,m;b&&(e=l*d,m=g*d,c.push({number:this.tiles[g][l],type:b,layer:this.name,position:new a.Point(e,m)}))}}});return 0<c.length?c:!1};this.setLayerBackgroundPosition=function(b,d,e){var c=G(b);d instanceof a.Point?c.backgroundPosition.copy(d):c.backgroundPosition.x(d).y(e);U.call(c,b);return this};this.setLayerBackgroundRepeat=function(b,a){var d=G(b);d.backgroundRepeat=a;U.call(d,b);return this};this.setLayerBackgroundAlias=function(b,a){var d=G(b);d.backgroundAlias=
a;U.call(d,b);return this};this.setLayerSpeed=function(b,a,d){b=G(b);b.hspeed=parseFloat(a||0,10);b.vspeed=parseFloat(d||0,10);return this};this.orderLayers=function(b){a.forEach(b,function(b){G(this).canvas.style.zIndex=b.key});return this};this.getScreen=function(){var b=E.createElement("canvas"),d=b.getContext("2d"),c=n.view(),e=c?c.position():new a.Point,m=c?c.width():n.getWidth(),f=c?c.height():n.getHeight();b.width=m;b.height=f;A.sort(function(b,a){return b.canvas.style.zIndex-a.canvas.style.zIndex});
a.forEach(A,function(){d.drawImage(this.canvas,parseInt(e.x()*this.hspeed,10),parseInt(e.y()*this.vspeed,10),m,f,0,0,m,f)});return b.toDataURL()};this.getTileType=function(b,a,c){c=G(c);var e=0;b=Math.floor(b/d);a=Math.floor(a/d);0<c.tiles.length&&c.tiles[a]&&c.tiles[a][b]&&(e=j[c.tileName].types[c.tiles[a][b]]);return e};this.run=function(){if(0===u.length)throw new RangeError("The game can't be launched because it contains no rooms.");R||(R=!0,g.addEventListener("mousemove",function(b){var a=b.pageX;
b=b.pageY;for(var d=n.view(),c=d?d.x():0,d=d?d.y():0,e=this,m=null,f=0,m=0;e&&1==e.nodeType;)f=(m=B.getComputedStyle(e))?parseInt(m.borderLeftWidth,10):0,m=m?parseInt(m.borderTopWidth,10):0,a-=(e.offsetLeft||0)+f-(e.scrollLeft||0),b-=(e.offsetTop||0)+m-(e.scrollTop||0),e=e.parentNode;H.x(a+c).y(b+d)},!1),g.addEventListener("mousedown",function(b){M("eventMouseDown",0===b.button?37:39)}),g.addEventListener("mouseup",function(b){b=0===b.button?37:39;var a=M("eventMouseUp",b),d=a===k?!1:!a,a=M("eventClick",
b),a=a===k?!1:!a;g.oncontextmenu=d||a?function(){return!1}:null}),E.addEventListener("keydown",function(b){b=b||B.event;var d=b.which||b.keyCode,c=!1,e=null;a.isKeyPressed(d)||(S.push(d),e=M("eventKeyDown",d),c=e===k?!1:!e);e=M("eventKeyPressed",d);e=e===k?!1:!e;if(c||e)return b.preventDefault(),!1}),E.addEventListener("keyup",function(b){b=b||B.event;b=b.which||b.keyCode;a.removeFromArray(b,S)&&M("eventKeyUp",b)}),E.addEventListener("keypress",function(b){b=b||B.event;var a=b.which||b.keyCode;if(37<=
a&&40>=a)return b.preventDefault(),!1}));this.goToFirstRoom();$();fa();return this};this.getMouse=function(){return H};this.addRooms=function(b){if(b instanceof Array)a.forEach(b,function(){if(this instanceof a.Room)u.push(this);else throw new TypeError("Trying to add objects which are not instances of Room.");});else if(b instanceof a.Room)u.push(b);else throw new TypeError("Game.addRomms() -> trying to add an object which is not an instance of Room.");return this};this.getRoom=function(b){return a.forEach(u,
function(){if(this.getName()==b)return this})||null};this.getRooms=function(){return u};this.getCurrentRoom=function(){return n};this.goToFirstRoom=function(){return this.goToRoom(u[0])};this.goToLastRoom=function(){return this.goToRoom(u[u.length-1])};this.goToNextRoom=function(){var b=0;a.forEach(u,function(d){if(this.getName()==n.getName())return b=d.key+1,a.KEYWORDS.BREAK});b>=u.length&&(b=0);return this.goToRoom(u[b])};this.goToPrevRoom=function(){var b=0;a.forEach(u,function(d){if(this.getName()==
n.getName())return b=d.key-1,a.KEYWORDS.BREAK});return 0>b?this.goToLastRoom():this.goToRoom(u[b])};this.restartRoom=function(){return this.goToRoom(n)};this.goToRoom=function(b){var c=null,c={};if(b instanceof a.Room)n=b;else if(c=this.getRoom(b))n=c;else throw new ReferenceError("This game doesn't have a room with name \""+b+'".');a.forEach(L,function(){e.instanceDestroy(this,!0)});aa();a.forEach(A,function(){this.animatedTiles.length=0;this.elements.length=0});T.length=0;b=n.getWidth();var c=n.getHeight(),
m=n.view(),f=m?m.width():b,m=m?m.height():c;g.setAttribute("data-jsglib-room-width",b);g.setAttribute("data-jsglib-room-height",c);g.style.width=f+"px";g.style.height=m+"px";y(!0,U);if(c=K[n.getName()])a.forEach(c.elements,function(){e.instanceCreate(this.x,this.y,this["class"],this.layer)}),a.forEach(c.tiles,function(b){var c=G(b.key);a.forEach(this,function(b){var m=b.key,f=j[m];c.tiles=this;c.tileName=m;c.spriteTile=f.sprite;c.spriteTile&&a.forEach(c.tiles,function(b){a.forEach(this,function(l){var g=
this,t=null,j=e.isTileAnimated(m,g),r=0;c.drawTile(b.key,l.key);if(!1!==j&&(r=f.animations[j].speed))t=(new a.Sprite(c.spriteTile.getImage())).makeTiles(d,d,f.separation).usedTiles(f.animations[j].tiles).imagespeed(r),a.forEach(t.usedTiles(),function(b){if(this==g)return t.imageindex(b.key),!0}),c.animatedTiles.push({position:new a.Point(b.key,l.key),sprite:t})})})})});n.eventStart();return this};this.fps=function(b){if(b===k)return m;m=parseInt(b,10);return this};this.getInstancesByType=function(b){if(!C[b])throw new ReferenceError('Game.getInstancesByType() -> Class "'+
b+'" is not defined in this game.');var d=[];a.forEach(w,function(){this.instanceOf(b)&&d.push(this)});return d};this.getInstancesIn=function(b){var d=[];a.forEach(w,function(){this.getRectangleRepresentation().isCollidedWithRectangle(b)&&d.push(this)});return d};this.getInstanceNearest=function(b,d,c){var e=null,m=-1,f=0;if((d=d||!1)&&!C[d])throw new ReferenceError('Game.getInstanceNearest() -> Class "'+d+'" is not defined in this game.');c=c||null;a.forEach(w,function(){if(d&&!this.instanceOf(d)||
c&&this.equals(c))return a.KEYWORDS.CONTINUE;f=b.getDistanceTo(this.getCenter());if(0>m||f<m)m=f,e=this});return e};this.instanceNumber=function(b){if(!C[b])throw new ReferenceError('Game.instanceNumber() -> Class "'+b+'" is not defined in this game.');return this.getInstancesByType(b).length};this.totalOfInstances=function(b){if(!b)return w.length;if(!C[b])throw new ReferenceError('Game.totalOfInstances() -> Class "'+b+'" is not defined in this game.');return this.getInstancesByType(b).length};this.isMouseOver=
function(b){return H.isInRectangle(b.getRectangleRepresentation())};this.drawObject=function(b,d,c,e,m){if(!b)throw new ReferenceError("Game.drawObject() -> given object seems to not exist.");var f=G(d);if(m||0<b.opacity())f=G(d),e&&(f.needRefresh=!0),c=c||new a.Point,T.push({object:b,position:c,layer:f,eraseMode:m});return this};this.eraseObject=function(b,a,d){if(!b)throw new ReferenceError("Game.eraseObject() -> given object seems to not exist.");return this.drawObject(b,a,d,!1,!0)};g=E.getElementById(c);
if(!g)throw new ReferenceError('new JSGlib.Game("'+c+'") -> id "'+c+'" does not exist.');g.style.overflow="hidden";g.style.display="block";q=B.getComputedStyle(g);if("static"==q.position||0===q.position.length)g.style.position="relative";V[c]=this;this.createLayer("main",!0)},Element:function(c,h,d,j){a.Element._isLoaded||(a.Element._isLoaded=!0,a.Element._lastId=0);var e=++a.Element._lastId,g=new a.Point(c,h),q=new a.Point(c,h),n=0,f=0,s=0,r=100,t=new a.Rectangle(c,h),l=null,u=a.STATE.STAND,K=!1,
Q=!1,R=!1,H=!0,L=!0,w=null,z={},x=null,D=e,A=!1,C=null;this.getId=function(){return e};this.getGame=function(){return j};this.zIndex=function(a){if(a===k)return D;a!=D&&(D=parseInt(a,10),j.orderElementsOnLayer(d).updateMaxZIndex(D));return this};this.putToFirstPlan=function(){j.putElementToFirstPlan(this);return this};this.destroy=function(a){j.instanceDestroy(this,a);return this};this.getRectangleRepresentation=function(){return t};this.active=function(a){if(a)j.activateElement(this);else if(!1===
a)j.deactivateElement(this);else return j.isElementActive(this);return this};this.callParent=function(a,d,c){return j.callParent(this,a,d,c)};this.instanceNearest=function(a){return j.getInstanceNearest(this.getCenter(),a,this)};this.isInsideRoom=function(){return j.isInsideRoom(this)};this.isInsideView=function(){return j.isInsideView(this)};this.isMouseOver=function(){return j.isMouseOver(this)};this.x=function(a){if(a===k)return t.x();t.x(a);return this};this.y=function(a){if(a===k)return t.y();
t.y(a);return this};this.width=function(a){if(a===k)return!l?t.width():l.isTiles()?l.getTilesWidth():l.getWidth();t.width(a);return this};this.height=function(a){if(a===k)return!l?t.height():l.isTiles()?l.getTilesHeight():l.getHeight();t.height(a);return this};this.position=function(d,c){if(d===k)return t.position();d instanceof a.Point?t.position().copy(d):t.position().x(d).y(c);K=!0;return this};this.prevPosition=function(a){if(a===k)return q;q.copy(a);return this};this.prevX=function(){return q.x()};
this.prevY=function(){return q.y()};this.startPosition=function(){return g};this.startX=function(){return g.x()};this.startY=function(){return g.y()};this.setAlarm=function(a,d,c){d=parseInt(d,10);if(c)return z[a]+=d,1>z[a]?(delete z[a],!0):!1;z[a]=d;return this};this.cancelAlarm=function(a){delete z[a];return this};this.getAlarms=function(){return z};this.filter=function(a){if(!a)return w;w=a;return this};this.getCenter=function(){return t.getCenter()};this.gravity=function(a){if(a===k)return n;
n=parseFloat(a,10);return this};this.hspeed=function(a){if(a===k)return f;f=parseFloat(a,10);return this};this.vspeed=function(a){if(a===k)return s;s=parseFloat(a,10);return this};this.getDirection=function(){return a.getVectorDirection(f,s)};this.moveToDirection=function(a,d){a=(360-a)*Math.PI/180;f=d*Math.cos(a);s=d*Math.sin(a);return this};this.moveToPoint=function(d,c,e){var f=parseInt(d.x(),10);d=parseInt(d.y(),10);var l=f-parseInt(this.x(),10),g=d-parseInt(this.y(),10);e&&(x={x:f,y:d,fromLeft:0<
l,fromTop:0<g,callback:e});return this.moveToDirection(a.getVectorDirection(l,g),c)};this.setPath=function(d,c,e){if(d[0]instanceof a.Point||d[0].point){var f=this,l=null;(function I(g){A=!0;if(l=d[g]instanceof a.Point?d[g]:d[g].point)f.moveToPoint(l,c,function(){d[g].callback&&d[g].callback.apply(f);if(d[++g])I(g);else if(e)if("string"==typeof e)switch(e){case a.KEYWORDS.REPEAT:I(0);break;case a.KEYWORDS.REVERSE:d.reverse(),d.push(d.shift()),I(0)}else A=!1,e.apply(f);else A=!1});else throw new TypeError('Element.setPath() -> point at index "'+
g+'" seems to not exist.');})(0)}else throw new TypeError('Element.setPath() -> first parameter must be an array of JSGlib.Point or an array of objects having a property "point" which is an instance of JSGlib.Point.');return this};this.cancelMoveToPointCallBack=function(){x=null;A=!1;return this};this.checkMoveToPointCallback=function(){if(x){var a=Math.floor(this.x()),d=Math.floor(this.y()),c=Math.abs(f),e=Math.abs(s);0<c&&0.1>c&&(f=0,this.x(x.x));0<e&&0.1>e&&(s=0,this.y(x.y));if((x.fromLeft&&a>=
x.x||!x.fromLeft&&a<=x.x)&&(x.fromTop&&d>=x.y||!x.fromTop&&d<=x.y))x.callback.apply(this),A||(x=null)}return this};this.opacity=function(a){if(a===k)return r;r=parseInt(a,10);K=!0;return this};this.solid=function(a){if(a===k)return R;R=a;return this};this.checkCollisions=function(a){if(a===k)return H;H=a;return this};this.stopOnSolids=function(a){if(a===k)return L;L=a;return this};this.maskColorForSolidCollisions=function(d){if(!d)return C;C=new a.Color(d);return this};this.getLayer=function(){return d};
this.sprite=function(d,c,e,f,g){if(!d)return l;d instanceof a.Sprite?l=d:(l=new a.Sprite(j.getImage(d)),c&&(l.makeTiles(c,e,f),g&&l.masks(j.getImage(g))));K=!0;t.height(l.isTiles()?l.getTilesHeight():l.getHeight());t.width(l.isTiles()?l.getTilesWidth():l.getWidth());return this};this.spriteModified=function(a){if(a===k)return K;K=a;return this};this.alwaysActive=function(a){if(a===k)return Q;Q=a;return this};this.equals=function(a){return a?a.getId?e==a.getId():!1:!1};this.instanceOf=function(d){return!!a.forEach(this._types,
function(){if(this==d)return!0})};this.isCollidedWithElement=function(d){var c=this,e=l?l.getCurrentMasks():[],f=d.sprite(),g=f?f.getCurrentMasks():[],j=l.getCurrentTilePosition(),r=f?f.getCurrentTilePosition():new a.Point,h=null,f=0===e.length,n=0===g.length,u=null,q={thisMasks:{},otherMasks:{},thisHasMasksCollided:!1,otherHasMasksCollided:!1},k=function(d,c,e,f,l){a.forEach(d,function(){var d=new a.Rectangle(this.rectangle);d.x(d.x()+c.x()-f.x()).y(d.y()+c.y()-f.y());e.getRectangleRepresentation().isCollidedWithRectangle(d)&&
(q[l+"Masks"][this.color]=!0,q[l+"HasMasksCollided"]=!0)})};if(t.isCollidedWithRectangle(d.getRectangleRepresentation())){if(!f&&!n)a.forEach(e,function(){u=new a.Rectangle(this.rectangle);u.x(u.x()+c.x()-j.x()).y(u.y()+c.y()-j.y());h=this;a.forEach(g,function(){var c=new a.Rectangle(this.rectangle);c.x(c.x()+d.x()-r.x()).y(c.y()+d.y()-r.y());u.isCollidedWithRectangle(c)&&(q.thisMasks[h.color]=!0,q.otherMasks[this.color]=!0,q.thisHasMasksCollided=!0,q.otherHasMasksCollided=!0)})});else if(!f||!n)f?
k(g,d,c,r,"other"):k(e,c,d,j,"this");return q}return!1};this.getMask=function(d){var c=this.sprite(),e=c?c.getCurrentMasks():[],f=null,l=null,f=null;if(0<e.length&&(f=d?a.forEach(e,function(){if(this.color===d)return this}):e[0]))l=new a.Rectangle(f.rectangle),f=c.getCurrentTilePosition(),l.x(l.x()-f.x()).y(l.y()-f.y());l||(l=(new a.Rectangle(t)).x(0).y(0));return l};this.state=function(a){if(a===k)return u;u=a;return this};this.isStateSTAND=function(){return u>=a.STATE.STAND&&u<=a.STATE.STAND_DOWN_RIGHT};
this.isStateMOVE=function(){return u>=a.STATE.MOVE&&u<=a.STATE.MOVE_DOWN_RIGHT};this.isStateHURT=function(){return u>=a.STATE.HURT&&u<=a.STATE.HURT_DOWN_RIGHT};this.isStateDEATH=function(){return u>=a.STATE.DEATH&&u<=a.STATE.DEATH_DOWN_RIGHT};this.isStateSLIP=function(){return u>=a.STATE.SLIP&&u<=a.STATE.SLIP_DOWN_RIGHT};this.isStateLEFT=function(){var a=u%10;return 1==a||5==a||7==a};this.isStateRIGHT=function(){var a=u%10;return 2==a||6==a||8==a};this.isStateUP=function(){var a=u%10;return 3==a||
5==a||6==a};this.isStateDOWN=function(){var a=u%10;return 4==a||7==a||8==a}},Sprite:function(c){if(!c)throw new ReferenceError("new Sprite() -> no image provided.");var h=[],d=[],j=0,e=0,g=0,q=0.1,n=0,f=null,s=function(a,d){var l=d.x(),g=d.y(),n=c.height%e,q=c.width%j,k=0,k=0;0<h.length&&(l=Math.round(Math.max(0,l-q)/j),g=Math.round(Math.max(0,g-n)/e),k=(c.width-q)/j,k=l+g*k+1);f[k]||(f[k]=[]);f[k].push({color:a,rectangle:d})};this.getImage=function(){return c};this.getWidth=function(){return c.width};
this.getHeight=function(){return c.height};this.getTilesWidth=function(){return j};this.getTilesHeight=function(){return e};this.getTilesSeparation=function(){return g};this.isTiles=function(){return 0<h.length};this.animate=function(){if(!this.isTiles()||0===q)return null;var a=n,c=parseInt(n,10),e=d.length;if(1==e)return null;a+=q;if(a>e)return n=0,1<e?!0:null;if(parseInt(a,10)>c)return n=c+1,!1;n=a;return null};this.makeTiles=function(c,f,l){l=l||0;for(var n=this.getWidth(),q=this.getHeight(),
k=0,s=0,H=0,s=0;s<q;s+=f){H=s/f;h[H]=[];for(k=0;k<n;k+=c)h[H][k/c]=new a.Point(k+l*(k/c),s+l*(s/f)),n-=l;n=this.getWidth();q-=l}j=c;e=f;g=l;d=[1];return this};this.usedTiles=function(a){if(a)a.toString()!=d.toString()&&(d=a,this.imageindex(0));else return d;return this};this.imagespeed=function(a){if(a===k)return q;q=a;return this};this.imageindex=function(a){if(a===k)return n;n=a;return this};this.getCurrentMasks=function(){if(f){var a=this.getCurrentTileNumber();return f[a]?f[a]:[]}return[]};this.masks=
function(d){if(!d)return f;var c=E.createElement("canvas"),e=c.getContext("2d"),g=[],j=null,n=null,h=null,q=null,k=null,w=0,z=0,x=a.KEYWORDS.NULL,D=0,A=0;f?f.length=0:f=[];c.width=d.width;c.height=d.height;e.drawImage(d,0,0);k=e.getImageData(0,0,d.width,d.height);for(A=k.data.length;D<A;D+=4)n=k.data[D],h=k.data[D+1],q=k.data[D+2],w=D/4,z=Math.floor(w/c.width),w%=c.width,g[z]||(g[z]=[]),255==n&&255==h&&255==q||1>k.data[D+3]?g[z][w]=null:(n=n.toString(16),h=h.toString(16),q=q.toString(16),n=2>n.length?
"0"+n:n,h=2>h.length?"0"+h:h,q=2>q.length?"0"+q:q,g[z][w]="#"+n+h+q);a.forEach(g,function(d){a.forEach(this,function(c){if(0!==x.localeCompare(this)){if(j){s(x,j.width(w));w=j.x();for(A=w+j.width();w<A;w++){z=j.y();for(k=z+j.height();z<k;z++)g[z][w]=null}j=null}x=this;if(!a.isSet(this))return a.KEYWORDS.CONTINUE;j=new a.Rectangle(c.key,d.key);w=1;for(A=d.key+1;;A++){if(!g[A]||g[A][c.key]!=x){j.height(w);break}w++}w=1}else a.isSet(x)&&w++})});j&&s(x,j.width(w));return this};this.getCurrentTileNumber=
function(){if(!this.isTiles())return 0;var a=parseInt(n,10);a>d.length&&(a=0);return d[a]||1};this.getCurrentTilePosition=function(){if(!this.isTiles())return new a.Point;var d=this.getCurrentTileNumber(),c=0;return a.forEach(h,function(){return a.forEach(this,function(){if(++c==d)return this})})}},Room:function(c,h,d){var j=null,e=0,g=0,q=null,n=null;this.getName=function(){return j};this.getWidth=function(){return e};this.getHeight=function(){return g};this.view=function(d,c,e,g){if(d===k)return q;
q=new a.Rectangle(d,c,e,g);return this};this.viewLinkedElement=function(a){if(a===k)return n;(n=a)&&a.getGame().checkElementsForActivation(!0);return this};this.eventStart=function(){};h!==k&&(j=c,e=h,g=d)},Point:function(c,h){var d=0,j=0;this.x=function(a){if(a===k)return d;d=parseFloat(a,10);return this};this.y=function(a){if(a===k)return j;j=parseFloat(a,10);return this};this.equals=function(d){return d instanceof a.Point?this.x()==d.x()&&this.y()==d.y():!1};this.copy=function(d){if(d instanceof
a.Point)return this.x(d.x()).y(d.y());throw new TypeError("Point.copy() -> given point is not an instance of Point.");};this.add=function(c,g){return c instanceof a.Point?this.x(d+c.x()).y(j+c.y()):this.x(d+(c||0)).y(j+(g||0))};this.substract=function(c,g){return c instanceof a.Point?this.x(d-c.x()).y(j-c.y()):this.x(d-(c||0)).y(j-(g||0));throw new TypeError("Point.substract() -> given point is not an instance of Point.");};this.isInRectangle=function(a){var d=this.x(),c=this.y(),j=a.x(),f=a.y(),
h=a.width();a=a.height();return d>=j&&d<j+h&&c>=f&&c<f+a};this.getDistanceTo=function(a){return Math.sqrt(Math.pow(d-a.x(),2)+Math.pow(j-a.y(),2))};c!==k&&(c instanceof a.Point?this.copy(c):this.x(c).y(h))},Rectangle:function(c,h,d,j){var e=new a.Point,g=0,q=0;this.position=function(d,c){if(d===k)return e;d instanceof a.Point?e.copy(d):e.x(d).y(c);return this};this.x=function(a){if(a===k)return e.x();e.x(a);return this};this.y=function(a){if(a===k)return e.y();e.y(a);return this};this.width=function(a){if(a===
k)return g;g=parseInt(a,10);return this};this.height=function(a){if(a===k)return q;q=parseInt(a,10);return this};this.getCenter=function(){return new a.Point(e.x()+g/2,e.y()+q/2)};this.isCollidedWithRectangle=function(a){var d=this.x(),c=this.y(),e=this.width(),g=this.height(),l=a.x(),j=a.y(),h=a.width();a=a.height();return!(l>=d+e||l+h<=d||j>=c+g||j+a<=c)};c!==k&&(c instanceof a.Rectangle?(this.position(c.position()),this.width(c.width()),this.height(c.height())):c instanceof a.Point?(this.position(c),
this.width(h),this.height(d)):(this.position(c,h),this.width(d),this.height(j)))},Drawing:{get BLENDING_MODES(){return{NORMAL:1,DIVIDE:2,SCREEN:3,OVERLAY:4,DODGE:5,BURN:6,HARD_LIGHT:7,GRAIN_EXTRACT:8,GRAIN_MERGE:9,AVERAGE:10,DIFFERENCES:11,ADDITION:12,SUBSTRACT:13,DARKEN_ONLY:14,LIGHTEN_ONLY:15,MULTIPLY:16}},get CANVAS_FILTER(){return Y},get CTX_FILTER(){return ha},Object:function(){var c=100,h=new a.Color("#000"),d="#000",j=0;this.opacity=function(a){if(a===k)return c;c=parseInt(a,10);return this};
this.color=function(d,c){if(!d)return h;h=new a.Color(d,c);return this};this.borderColor=function(c,g){if(!c)return d;d=new a.Color(c,g);return this};this.borderSize=function(a){if(a===k)return j;j=a;return this};this.draw=function(){throw Error("Class \"Drawing.Object\" shouldn't be directly called! You should use an inherited class from this one. Or maybe the inherited class doesn't overwritte the method draw()?");}},Rectangle:function(c,h){a.Drawing.Object.call(this);var d=c||1,j=h||1;this.width=
function(a){if(a===k)return d;d=parseInt(a,10);return this};this.height=function(a){if(a===k)return j;j=parseInt(a,10);return this};this.draw=function(a,c,h){a.fillRect(c.x(),c.y(),d,j);h&&a.strokeRect(h.x(),h.y(),d,j)}},Line:function(c,h){a.Drawing.Object.call(this);this.borderSize(1);var d=new a.Point(c),j=new a.Point(h);this.firstPoint=function(a){if(!a)return d;d.copy(a);return this};this.secondPoint=function(a){if(!a)return j;j.copy(a);return this};this.color=function(a,d){return this.borderColor(a,
d)};this.draw=function(a,c,h){h&&(c=h.x(),h=h.y(),a.beginPath(),a.moveTo(c+d.x(),h+d.y()),a.lineTo(c+j.x(),h+j.y()),a.stroke())}},Circle:function(c){a.Drawing.Object.call(this);var h=c;this.radius=function(a){if(!a)return h;h=a;return this};this.draw=function(a,c,e){a.beginPath();a.arc(c.x(),c.y(),h,0,360,!1);a.closePath();a.fill();e&&a.stroke()}},Shape:function(c){a.Drawing.Object.call(this);var h=c.slice(0);this.points=function(a){if(!a)return h;h=a;return this};this.draw=function(d,c,e){var g=
c.x(),q=c.y();d.beginPath();a.forEach(h,function(a){d[0<a.key?"lineTo":"moveTo"](g+this.x(),q+this.y())});d.closePath();d.fill();e&&d.stroke()}},Text:function(c,h,d,j){a.Drawing.Object.call(this);var e=c+""||"",g=h||"20px Calibri",q=parseInt(d,10)||0,n=parseInt(j,10)||20;this.text=function(a){if(a===k)return e;e=a+"";return this};this.font=function(a){if(!a)return g;g=a;return this};this.maxWidth=function(a){if(a===k)return q;q=parseInt(a,10);return this};this.lineHeight=function(a){if(a===k)return n;
n=parseInt(a,10);return this};this.getLines=function(){var d=e.split("\n"),c=E.createElement("canvas").getContext("2d");c.textBaseline="top";c.font=g;c.lineWidth=this.borderSize();0<q&&a.forEach(d,function(a){var e=c.measureText(this).width,l="",g=-1,h="",j="",n=[],k=0;if(e>q){n=this.split(" ");k=n.length;do if(h=j,j+=n[++g]+" ",c.measureText(j).width>q||g==k)l+=h+"\n",j=n[g]+" ";while(g<e);d[a.key]=l}else d[a.key]+="\n"});return d};this.numberOfLines=function(){return this.getLines().length};this.getWidth=
function(){var a=E.createElement("canvas").getContext("2d"),c=0;a.textBaseline="top";a.font=g;a.lineWidth=this.borderSize();c=a.measureText(e).width;return q<c&&0<q?d:c};this.getHeight=function(){return this.numberOfLines()*n};this.draw=function(d,c,e){var j=e?e.x():0,l=e?e.y():0,h=c.x(),k=c.y();d.font=g;a.forEach(this.getLines(),function(a){e&&d.strokeText(this,j,l+a.key*n+n);d.fillText(this,h,k+a.key*n+n)})}},Sprite:function(c){a.Drawing.Object.call(this);var h=c,d=null;this.sprite=function(a){if(!a)return h;
h=a;return this};this.filter=function(a){if(!a)return d;d=a;return this};this.draw=function(c,e){var g=new a.Point(0,0),k=h.getTilesWidth(),n=h.getTilesHeight(),f=0,s=0,r=h.getImage();h.animate();h.isTiles()&&g.copy(h.getCurrentTilePosition());f=g.x();s=g.y();c.drawImage(r,f,s,k,n,e.x(),e.y(),k,n);d&&(a.Drawing.CANVAS_FILTER.width=k,a.Drawing.CANVAS_FILTER.height=n,a.Drawing.CTX_FILTER.drawImage(r,f,s,k,n,0,0,k,n),d.draw(c,e))}},Filter:function(c){a.Drawing.Object.call(this);var h=c||1;this.mode=
function(a){if(!a)return h;h=a;return this};this.draw=function(d,c){for(var e=a.Drawing.CTX_FILTER.getImageData(0,0,a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height),g=0,k=e.data.length,n=new a.Color(this.color()),f=n.getRGB(),s=function(){switch(h){case a.Drawing.BLENDING_MODES.MULTIPLY:return function(a,d,c){return{red:a*f.red/255,green:d*f.green/255,blue:c*f.blue/255}};case a.Drawing.BLENDING_MODES.DIVIDE:return function(a,d,c){return{red:Math.min(255,256*a/(f.red+1)),green:Math.min(255,
256*d/(f.green+1)),blue:Math.min(255,256*c/(f.blue+1))}};case a.Drawing.BLENDING_MODES.SCREEN:return function(a,d,c){return{red:255-(255-f.red)*(255-a)/255,green:255-(255-f.green)*(255-d)/255,blue:255-(255-f.blue)*(255-c)/255}};case a.Drawing.BLENDING_MODES.OVERLAY:return function(a,d,c){return{red:a/255*(a+2*f.red/255*(255-a)),green:d/255*(d+2*f.green/255*(255-d)),blue:c/255*(c+2*f.blue/255*(255-c))}};case a.Drawing.BLENDING_MODES.DODGE:return function(a,d,c){return{red:Math.min(255,256*a/(255-f.red+
1)),green:Math.min(255,256*d/(255-f.green+1)),blue:Math.min(255,256*c/(255-f.blue+1))}};case a.Drawing.BLENDING_MODES.BURN:return function(a,d,c){return{red:Math.max(0,255-256*(255-a)/(f.red+1)),green:Math.max(0,255-256*(255-d)/(f.green+1)),blue:Math.max(0,255-256*(255-c)/(f.blue+1))}};case a.Drawing.BLENDING_MODES.HARD_LIGHT:return function(a,d,c){return{red:128<f.red?255-(255-2*(f.red-128))*(255-a)/256:Math.min(255,2*f.red*a/256),green:128<f.green?255-(255-2*(f.green-128))*(255-d)/256:Math.min(255,
2*f.green*d/256),blue:128<f.blue?255-(255-2*(f.blue-128))*(255-c)/256:Math.min(255,2*f.blue*c/256)}};case a.Drawing.BLENDING_MODES.GRAIN_EXTRACT:return function(a,d,c){return{red:Math.min(255,Math.max(0,a-f.red+128)),green:Math.min(255,Math.max(0,d-f.green+128)),blue:Math.min(255,Math.max(0,c-f.blue+128))}};case a.Drawing.BLENDING_MODES.GRAIN_MERGE:return function(a,d,c){return{red:Math.min(255,Math.max(0,a+f.red-128)),green:Math.min(255,Math.max(0,d+f.green-128)),blue:Math.min(255,Math.max(0,c+f.blue-
128))}};case a.Drawing.BLENDING_MODES.AVERAGE:return function(a,d,c){return{red:(a+f.red)/2,green:(d+f.green)/2,blue:(c+f.blue)/2}};case a.Drawing.BLENDING_MODES.DIFFERENCES:return function(a,d,c){return{red:Math.abs(a-f.red),green:Math.abs(d-f.green),blue:Math.abs(c-f.blue)}};case a.Drawing.BLENDING_MODES.ADDITION:return function(a,d,c){return{red:Math.min(255,a+f.red),green:Math.min(255,d+f.green),blue:Math.min(255,c+f.blue)}};case a.Drawing.BLENDING_MODES.SUBSTRACT:return function(a,d,c){return{red:Math.max(0,
a-f.red),green:Math.max(0,d-f.green),blue:Math.max(0,c-f.blue)}};case a.Drawing.BLENDING_MODES.DARKEN_ONLY:return function(a,d,c){return{red:Math.min(a,f.red),green:Math.min(d,f.green),blue:Math.min(c,f.blue)}};case a.Drawing.BLENDING_MODES.LIGHTEN_ONLY:return function(a,d,c){return{red:Math.max(a,f.red),green:Math.max(d,f.green),blue:Math.max(c,f.blue)}};default:return function(){return{red:f.red,green:f.green,blue:f.blue}}}}();g<k;g+=4)0<e.data[g+3]&&(n=s(e.data[g],e.data[g+1],e.data[g+2]),e.data[g]=
n.red,e.data[g+1]=n.green,e.data[g+2]=n.blue);a.Drawing.CTX_FILTER.putImageData(e,0,0);d.globalAlpha=this.opacity()/100;d.drawImage(a.Drawing.CANVAS_FILTER,0,0,a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height,c.x(),c.y(),a.Drawing.CANVAS_FILTER.width,a.Drawing.CANVAS_FILTER.height)}}},Color:function(c,h){var d=0,j=0,e=0,g=0,k=0,n=0,f=null,s=function(){var a=n/100,c=k/100,h=g/60,c=(1-Math.abs(2*a-1))*c,r=c*(1-Math.abs(h%2-1)),a=a-c/2;0<=h&&1>h?(d=c,j=r,e=0):1<=h&&2>h?(d=r,j=c,e=0):2<=h&&
3>h?(d=0,j=c,e=r):3<=h&&4>h?(d=0,j=r,e=c):4<=h&&5>h?(d=r,j=0,e=c):5<=h&&6>h?(d=c,j=0,e=r):e=j=d=0;d=Math.round(255*(d+a));j=Math.round(255*(j+a));e=Math.round(255*(e+a));f=null},r=function(){var a=d/255,c=j/255,h=e/255,r=Math.min(a,c,h),s=Math.max(a,c,h),y=s-r,B=0,E=0,w=0;n=(r+s)/2;0===y?k=g=0:(k=0.5>n?y/(s+r):y/(2-s-r),B=((s-a)/6+y/2)/y,E=((s-c)/6+y/2)/y,w=((s-h)/6+y/2)/y,a==s?g=w-E:c==s?g=1/3+B-w:h==s&&(g=2/3+E-B),0>g?g+=1:1<g&&(g-=1),g=parseInt(Math.round(360*g),10),k=parseInt(Math.round(100*k),
10));n=parseInt(Math.round(100*n),10);f=null};this.getHexadecimal=function(){if(!f){var a=d.toString(16),c=j.toString(16),g=e.toString(16);f="#"+((2>a.length?"0"+a:a)+(2>c.length?"0"+c:c)+(2>g.length?"0"+g:g)).toLowerCase()}return f};this.getRGB=function(){return{red:d,green:j,blue:e}};this.getHSL=function(){return{hue:g,saturation:k,lightness:n}};this.setRed=function(a,c){var e=d;d=c?d+a:a;d=Math.min(255,Math.max(0,parseInt(d,10)));e!=d&&r();return this};this.setGreen=function(a,c){var d=j;j=c?j+
a:a;j=Math.min(255,Math.max(0,parseInt(j,10)));d!=j&&r();return this};this.setBlue=function(a,c){var d=e;e=c?e+a:a;e=Math.min(255,Math.max(0,parseInt(e,10)));d!=e&&r();return this};this.setHue=function(a,c){var d=g;g=c?g+a:a;g=Math.min(359,Math.max(0,parseInt(g,10)));d!=g&&s();return this};this.setSaturation=function(a,c){var d=k;k=c?k+a:a;k=Math.min(100,Math.max(0,parseInt(k,10)));d!=k&&s();return this};this.setLightness=function(a,c){var d=n;n=c?n+a:a;n=Math.min(100,Math.max(0,parseInt(n,10)));
d!=n&&s();return this};this.equals=function(a){return a?a.getHexadecimal?this.getHexadecimal()==a.getHexadecimal():!1:!1};if(c instanceof Array)h?(g=c[0],k=c[1],n=c[2],s()):(d=c[0],j=c[1],e=c[2],r());else if(c instanceof a.Color)d=c.getRGB(),j=d.green,e=d.blue,d=d.red,g=c.getHSL(),k=g.saturation,n=g.lightness,g=g.hue;else{c=c.toUpperCase();if(a.Color.NAMES[c])c=a.Color.NAMES[c];else if("#"!=c.charAt(0))throw Error('new Color() -> color "'+c+'" is not a valid color.');c=c.substr(1).toLowerCase();3==
c.length?(d=parseInt(c.charAt(0)+c.charAt(0),16),j=parseInt(c.charAt(1)+c.charAt(1),16),e=parseInt(c.charAt(2)+c.charAt(2),16)):(d=parseInt(c.charAt(0)+c.charAt(1),16),j=parseInt(c.charAt(2)+c.charAt(3),16),e=parseInt(c.charAt(4)+c.charAt(5),16));r()}}};Object.defineProperty(a.Color,"NAMES",{get:function(){return{ALICEBLUE:"#f0f8ff",ANTIQUEWHITE:"#faebd7",AQUA:"#0ff",AQUAMARINE:"#7fffd4",AZURE:"#f0ffff",BEIGE:"#f5f5dc",BISQUE:"#ffe4c4",BLACK:"#000",BLANCHEDALMOND:"#ffebcd",BLUE:"#00f",BLUEVIOLET:"#8a2be2",
BROWN:"#a52a2a",BURLYWOOD:"#deb887",CADETBLUE:"#5f9ea0",CHARTREUSE:"#7fff00",CHOCOLATE:"#d2691e",CORAL:"#ff7f50",CORNFLOWERBLUE:"#6495ed",CORNSILK:"#fff8dc",CRIMSON:"#dc143c",CYAN:"#0ff",DARKBLUE:"#00008b",DARKCYAN:"#008b8b",DARKGOLDENROD:"#b8860b",DARKGRAY:"#a9a9a9",DARKGREY:"#a9a9a9",DARKGREEN:"#006400",DARKKHAKI:"#bdb76b",DARKMAGENTA:"#8b008b",DARKOLIVEGREEN:"#556b2f",DARKORANGE:"#ff8c00",DARKORCHID:"#9932cc",DARKRED:"#8b0000",DARKSALMON:"#e9967a",DARKSEAGREEN:"#8fbc8f",DARKSLATEBLUE:"#483d8b",
DARKSLATEGRAY:"#2f4f4f",DARKSLATEGREY:"#2f4f4f",DARKTURQUOISE:"#00ced1",DARKVIOLET:"#9400d3",DEEPPINK:"#ff1493",DEEPSKYBLUE:"#00bfff",DIMGRAY:"#696969",DIMGREY:"#696969",DODGERBLUE:"#1e90ff",FIREBRICK:"#b22222",FLORALWHITE:"#fffaf0",FORESTGREEN:"#228b22",FUCHSIA:"#f0f",GAINSBORO:"#dcdcdc",GHOSTWHITE:"#f8f8ff",GOLD:"#ffd700",GOLDENROD:"#daa520",GRAY:"#808080",GREY:"#808080",GREEN:"#008000",GREENYELLOW:"#adff2f",HONEYDEW:"#f0fff0",HOTPINK:"#ff69b4",INDIANRED:"#cd5c5c",INDIGO:"#4b0082",IVORY:"#fffff0",
KHAKI:"#f0e68c",LAVENDER:"#e6e6fa",LAVENDERBLUSH:"#fff0f5",LAWNGREEN:"#7cfc00",LEMONCHIFFON:"#fffacd",LIGHTBLUE:"#add8e6",LIGHTCORAL:"#f08080",LIGHTCYAN:"#e0ffff",LIGHTGOLDENRODYELLOW:"#fafad2",LIGHTGRAY:"#d3d3d3",LIGHTGREY:"#d3d3d3",LIGHTGREEN:"#90ee90",LIGHTPINK:"#ffb6c1",LIGHTSALMON:"#ffa07a",LIGHTSEAGREEN:"#20b2aa",LIGHTSKYBLUE:"#87cefa",LIGHTSLATEGRAY:"#778899",LIGHTSLATEGREY:"#778899",LIGHTSTEELBLUE:"#b0c4de",LIGHTYELLOW:"#ffffe0",LIME:"#0f0",LIMEGREEN:"#32cd32",LINEN:"#faf0e6",MAGENTA:"#f0f",
MAROON:"#800000",MEDIUMAQUAMARINE:"#66cdaa",MEDIUMBLUE:"#0000cd",MEDIUMORCHID:"#ba55d3",MEDIUMPURPLE:"#9370db",MEDIUMSEAGREEN:"#3cb371",MEDIUMSLATEBLUE:"#7b68ee",MEDIUMSPRINGGREEN:"#00fa9a",MEDIUMTURQUOISE:"#48d1cc",MEDIUMVIOLETRED:"#c71585",MIDNIGHTBLUE:"#191970",MINTCREAM:"#f5fffa",MISTYROSE:"#ffe4e1",MOCCASIN:"#ffe4b5",NAVAJOWHITE:"#ffdead",NAVY:"#000080",OLDLACE:"#fdf5e6",OLIVE:"#808000",OLIVEDRAB:"#6b8e23",ORANGE:"#ffA500",ORANGERED:"#ff4500",ORCHID:"#da70d6",PALEGOLDENROD:"#eee8aa",PALEGREEN:"#98fb98",
PALETURQUOISE:"#afeeee",PALEVIOLETRED:"#db7093",PAPAYAWHIP:"#ffefd5",PEACHPUFF:"#ffdab9",PERU:"#cd853f",PINK:"#ffc0cb",PLUM:"#dda0dd",POWDERBLUE:"#b0e0e6",PURPLE:"#800080",RED:"#f00",ROSYBROWN:"#bc8f8f",ROYALBLUE:"#4169e1",SADDLEBROWN:"#8b4513",SALMON:"#fa8072",SANDYBROWN:"#f4a460",SEAGREEN:"#2e8b57",SEASHELL:"#fff5ee",SIENNA:"#a0522d",SILVER:"#c0c0c0",SKYBLUE:"#87ceeb",SLATEBLUE:"#6a5acd",SLATEGRAY:"#708090",SLATEGREY:"#708090",SNOW:"#fffafa",SPRINGGREEN:"#00ff7f",STEELBLUE:"#4682b4",TAN:"#d2b48c",
TEAL:"#008080",THISTLE:"#d8bfd8",TOMATO:"#ff6347",TURQUOISE:"#40e0D0",VIOLET:"#ee82ee",WHEAT:"#f5deb3",WHITE:"#fff",WHITESMOKE:"#f5f5f5",YELLOW:"#ff0",YELLOWGREEN:"#9acd32"}}});B.JSGlib=a})(window,document);