/*!
 * JSGlib v3.0 (minified), JavaScript Library
 *
 * Copyright 2011-2013, Adrien Guéret
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * 
 * Date: 07/07/2013
 */
(function(C,x,m){var c={},F={},G=[],E={Pf:1,nf:2},H=x.createElement("canvas"),K=H.getContext("2d"),L=2,D=navigator.nb?navigator.nb:navigator.language,I=D.indexOf("-"),q={Ca:10,uf:11,vf:12,wf:13,rf:14,xf:15,yf:16,sf:17,tf:18,ce:20,ge:21,he:22,ie:23,de:24,je:25,ke:26,ee:27,fe:28,Wc:30,$c:31,ad:32,bd:33,Xc:34,cd:35,dd:36,Yc:37,Zc:38,nc:40,rc:41,sc:42,tc:43,oc:44,uc:45,vc:46,pc:47,qc:48,df:50,hf:51,jf:52,kf:53,ef:54,lf:55,mf:56,ff:57,gf:58},D=-1<I?D.substr(0,I):D,c={get Gf(){return E},get Lf(){return D},
get g(){return{W:"JSGLIB_BREAK",X:"JSGLIB_CONTINUE",F:"JSGLIB_NULL",Y:"JSGLIB_UNDEFINED",REPEAT:"JSGLIB_REPEAT",Ne:"JSGLIB_REVERSE"}},get oa(){return{pe:0,Le:1,Me:2,REPEAT:3}},get md(){return{Cf:9,Cc:13,Xe:16,Rb:17,Mb:17,tb:18,Jb:20,pf:32,sd:37,Kf:38,Oe:39,Bc:40,rb:65,yb:66,Hb:67,Ub:68,E:69,Dc:70,Jc:71,Tc:72,ed:73,jd:74,ld:75,od:76,Nd:77,le:78,qe:79,xe:80,Q:81,Je:82,Re:83,Bf:84,Jf:85,Mf:86,Of:87,Tf:88,Uf:89,Xf:90}},get Da(){return q},Yf:function(a){var f=10,e=0;a=a.toUpperCase();if(q[a])throw new ReferenceError('JSGlib.addStateConstant() => constant "'+
a+'" already exists.');c.forEach(q,function(){this>f&&0===this%10&&(f=this)});e=f+=10;q[a]=f;a+="_";q[a+"LEFT"]=++f;q[a+"RIGHT"]=++f;q[a+"UP"]=++f;q[a+"DOWN"]=++f;q[a+"UP_LEFT"]=++f;q[a+"UP_RIGHT"]=++f;q[a+"DOWN_LEFT"]=++f;q[a+"DOWN_RIGHT"]=++f;c.Element.prototype["isState"+a]=function(){var a=this.state();return a>=e&&a<=f};return c},cg:function(a){a=a.valueOf();return c.forEach(G,function(){if(this.valueOf()==a)return!0})||!1},ag:function(a,f){var e=c.B(a,G);e&&!f&&c.forEach(F,function(){this.Na(a)});
return e},Ya:function(a){return null===a||a==c.g.F},Za:function(a){return a===m||a==c.g.Y},ja:function(a){return!c.Ya(a)&&!c.Za(a)},Qa:function(a,c){var e=Math.atan2(-c,a)/(Math.PI/180);return 0>e?e+360:e},B:function(a,f,e){e=e||function(a,c){return a==c};return c.forEach(f,function(c){if(e(a,this))return f.splice(c.key,1),!0})||!1},hg:function(a,f){var e={},g=[];c.forEach(a,function(){e[f?this.l():this]=this});c.forEach(e,function(){g.push(this)});return g},Z:function(a){function f(a,d,e){a=e===
m?a:e+"["+a+"]";if("object"==typeof d.valueOf()){var b="";c.forEach(d,function(c){b+=f(c.key,this,a)});return b}return a+"="+d+"&"}var e=C.XMLHttpRequest?new XMLHttpRequest:new C.ActiveXObject("Microsoft.XMLHTTP"),g="",d=!0;c.forEach({url:"./",async:!0,type:"POST",dataType:"TEXT",data:{},dg:function(){},P:function(){},R:function(){},eg:function(){}},function(c){a[c.key]===m&&(a[c.key]=this)});d="POST"==a.type;a.dataType=a.dataType.toUpperCase();e&&(c.forEach(a.data,function(a){g+=f(a.key,this)}),
g=g.substr(0,g.length-1),e.onreadystatechange=function(){4==e.readyState&&(200==e.status||304==e.status?a.R("JSON"==a.dataType?JSON.parse(e.responseText):"XML"==a.dataType?e.responseXML:e.responseText):a.P(e))},e.open(a.type,a.url+(d?"":"?"+g),a.async),d&&e.setRequestHeader("Content-type","application/x-www-form-urlencoded"),e.send(d?g:null));return this},random:function(a,c){var e=0;a>c&&(e=c,c=a,a=e);return Math.floor((1+c-a)*Math.random())+a},forEach:function(a,f,e){function g(d,b){var e=a[d];
b.key=d;e===m?e=c.g.Y:null===e&&(e=c.g.F);return f.call(e.valueOf(),b)}var d="",k=0,h=null;e={values:e};if(a instanceof Array||a instanceof C.NodeList)for(k=a.length,d=0;d<k;d++){if(h=g(d,e),h!==m)if(h==c.g.W)break;else if(h!=c.g.X)return h}else for(d in a)if(a.hasOwnProperty(d)&&(h=g(d,e),h!==m))if(h==c.g.W)break;else return h},Sc:function(a,f){function e(b){var a=c.forEach(t,function(){if(this.name==b)return this});if(a)return a;throw new ReferenceError('Layer naming "'+b+'" is not defined for this game.');
}function g(b){c.forEach(w,function(){var a=b;this.eventKeyUp&&(a instanceof Array||(a=[a]),this.eventKeyUp.apply(this,a))})}function d(){c.forEach(t,function(){this.canvas.width=b.getAttribute("data-jsglib-room-width");this.canvas.height=b.getAttribute("data-jsglib-room-height");this.cb=!1;var a=this;0<this.aa.length&&c.forEach(this.aa,function(){var b=0,c=0;null!==this.C.$()&&(b=this.position.x(),c=this.position.y(),a.s[this.jb][b][c]=this.C.ea(),a.Ma(b,c,this.jb))})})}if(!a)throw new ReferenceError("new JSGlib.Game(idContainer) -> please provide a paramater.");
if(F[a])throw Error('Container with id "'+a+'" already contains a game.');var k=f?parseInt(f,10):16,h={},l=this,b=null,p=null,A={},u={},n=[],v=[],z=[],M=new c.b,w=[],r=[],t=[],J={},q=0,y=0;this.ba=function(b,a,c,d){if(d){if(!b.Ua(d))throw new TypeError('Game.callParent() -> instance of types "['+b.H+']" is not an instance of "'+d+'".');}else d=b.H[b.H.length-2];if(J[d].prototype[a])return c=c===m?[]:c,c instanceof Array||(c=[c]),J[d].prototype[a].apply(b,c);throw new ReferenceError('Game.callParent() -> class "'+
d+'" has no methods named "'+a+'".');};this.gb=function(b){e(b).elements.sort(function(b,a){return b.zIndex()-a.zIndex()});return this};this.lb=function(b){b>y&&(y=b)};this.Na=function(b){g(b)};this.O=function(b){return r[b.l()]};this.Ha=function(b){this.O(b)||(w.push(b),r[b.l()]=!0)};this.La=function(b){this.O(b)&&(c.B(b,w,function(b,a){return b.K(a)}),r[b.l()]=!1)};this.load=function(a,v,n){function f(){v&&g();n&&z==p&&setTimeout(function(){n.call(l)},500)}function g(){var a=parseInt(100*z/p,10),
c=e("main").J;b.setAttribute("data-jsglib-room-width",500);b.setAttribute("data-jsglib-room-height",30);b.style.width="500px";b.style.height="30px";d();c.fillStyle="#ff0000";c.rect(0,0,500*a/100,30);c.fill();c.fillStyle="#000";c.font="bold 20px Calibri";c.fillText(a+"%",250,20)}v=v===m?!0:v;a=a||{};a.images=a.images||{};a.U=a.U||{};a.s=a.s||[];a.S=a.S||[];var p=a.s.length+a.S.length,z=0;c.forEach(a.images,function(){p++});c.forEach(a.U,function(){p++});0<p?(v&&g(),c.forEach(a.images,function(a){var b=
new Image;b.src=this;A[a.key]=b;b.onload=function(){z++;f()}}),c.forEach(a.U,function(a){var d=x.createElement("audio");d.fg="auto";b.appendChild(d);c.forEach(this,function(){var a=x.createElement("source"),b="";switch(this.substring(this.lastIndexOf(".")+1)){case "mp3":b="audio/mpeg";break;case "wav":b="audio/wav";break;case "ogg":b="audio/ogg"}0<d.canPlayType(b).length&&(a.src=this,d.appendChild(a))});u[a.key]={ca:d,volume:1,fb:null,loop:!0};z++;f()}),c.forEach(a.s,function(){c.Z({url:this,async:!1,
dataType:"JSON",P:function(){throw Error('An Ajax error occurs while loading tiles "'+this+'".');},R:function(b){c.forEach(b,function(b){function a(b){e.ka(k,k,n.la);c.forEach(n.T,function(b){n.T[b.key]["function"]=d(this["function"][0],this["function"][1])});h[b]={C:e,Ja:n.Ja,T:n.T,la:n.la,types:{}};c.forEach(n.types,function(a){var d=a.key;E[d]||(E[d]=++L);c.forEach(this,function(){h[b].types[this]=E[d]})});z++;f()}function d(b,a){return function(c){return b*c+a}}p++;var v=l.m(this.bg),e=new c.A(v),
n=this;(function(b){v.complete?a(b):v.addEventListener("load",function(){a(b)})})(b.key)});z++}})}),c.forEach(a.S,function(){c.Z({url:this,async:!1,dataType:"JSON",P:function(){throw Error('An Ajax error occurs while loading level "'+this+'".');},R:function(b){var a=new c.G(b.name,b.width,b.height);0<b.pb&&0<b.ob&&a.view(b.ig,b.jg,b.pb,b.ob);l.Ia(a);z++;f()}})})):n&&n.call(l);return this};this.m=function(b){return A[b]||null};this.kb=function(b){return b?c.forEach(n,function(){if(this==b)return!0})||
!1:0<n.length};this.hb=function(b,a){var d=u[b],e=null;if(d&&d.ca)e=d.ca,this.kb(b)?e.currentTime=0:(n.push(b),u[b].fb=a,u[b].loop=!0,c.B(b,v)),e.play(),e.addEventListener("ended",function N(){e.removeEventListener("ended",N,!1);c.B(b,n);a&&a.apply(l);e.currentTime=0;l.hb(b,a)},!1);else throw new ReferenceError('Game.playSound() -> Sound "'+b+'" is not defined in this game.');};this.Ka=function(){var a=x.createElement("canvas"),d=a.getContext("2d"),v=q++;a.id="jsglib-layer-main";a.style.position=
"absolute";a.style.zIndex=v;a.style.left=0;a.style.top=0;a.width=0;a.height=0;d.textBaseline="top";b.appendChild(a);t.push({name:"main",canvas:a,J:d,elements:[],s:{},aa:[],V:{},cb:!0,Ra:1,qb:1,$f:!0,Zf:null,backgroundRepeat:c.oa.REPEAT,backgroundPosition:new c.b,Ma:function(b,a,d){var v=this.s[d][b][a],e=new c.b(0,0);a*=k;b*=k;0<v&&(this.V[d].mb([v]),e.v(this.V[d].fa()),this.J.clearRect(a,b,k,k),this.J.drawImage(this.V[d].m(),e.x(),e.y(),k,k,a,b,k,k))}})};this.Ia=function(b){if(b instanceof Array)c.forEach(b,
function(){if(this instanceof c.G)z.push(this);else throw new TypeError("Trying to add objects which are not instances of Room.");});else if(b instanceof c.G)z.push(b);else throw new TypeError("Game.addRomms() -> trying to add an object which is not an instance of Room.");};this.ia=function(b){return M.Va(b.Pa())};b=x.getElementById(a);if(!b)throw new ReferenceError('new JSGlib.Game("'+a+'") -> id "'+a+'" does not exist.');b.style.overflow="hidden";b.style.display="block";p=C.getComputedStyle(b);
if("static"==p.position||0===p.position.length)b.style.position="relative";F[a]=this;this.Ka()},Element:function(a,f,e,g){c.Element.Fa||(c.Element.Fa=!0,c.Element.Ga=0);var d=++c.Element.Ga;new c.b(a,f);new c.b(a,f);var k=0,h=0,l=100,b=new c.u(a,f),p=null,A=c.Da.Ca,u=null,n=d;this.l=function(){return d};this.zIndex=function(b){if(b===m)return n;b!=n&&(n=parseInt(b,10),g.gb(e).lb(n));return this};this.Pa=function(){return b};this.active=function(b){if(b)g.Ha(this);else if(!1===b)g.La(this);else return g.O(this);
return this};this.ba=function(b,a,c){return g.ba(this,b,a,c)};this.Wa=function(){return g.Wa()};this.Xa=function(){return g.Xa()};this.ia=function(){return g.ia(this)};this.x=function(a){if(a===m)return b.x();b.x(a);return this};this.y=function(a){if(a===m)return b.y();b.y(a);return this};this.width=function(a){if(a===m)return p?p.j()?p.N():p.o():b.width();b.width(a);return this};this.height=function(a){if(a===m)return p?p.j()?p.M():p.w():b.height();b.height(a);return this};this.position=function(a,
d){if(a===m)return b.position();a instanceof c.b?b.position().v(a):b.position().x(a).y(d);return this};this.filter=function(b){if(!b)return u;u=b;return this};this.da=function(){return b.da()};this.Ra=function(b){if(b===m)return k;k=parseFloat(b,10);return this};this.qb=function(b){if(b===m)return h;h=parseFloat(b,10);return this};this.bb=function(b,a){b=(360-b)*Math.PI/180;k=a*Math.cos(b);h=a*Math.sin(b);return this};this.moveToPoint=function(b,a){var d=parseInt(b.x(),10),e=parseInt(b.y(),10),d=
d-parseInt(this.x(),10),e=e-parseInt(this.y(),10);return this.bb(c.Qa(d,e),a)};this.opacity=function(b){if(b===m)return l;l=parseInt(b,10);return this};this.C=function(a,d,e,n,k){if(!a)return p;a instanceof c.A?p=a:(p=new c.A(g.m(a)),d&&(p.ka(d,e,n),k&&p.ab(g.m(k))));b.height(p.j()?p.M():p.w());b.width(p.j()?p.N():p.o());return this};this.K=function(b){return b?b.l?d==b.l():!1:!1};this.Ua=function(b){return!!c.forEach(this.H,function(){if(this==b)return!0})};this.state=function(b){if(b===m)return A;
A=b;return this}},A:function(a){function f(b,c){var f=c.x(),u=c.y(),n=a.height%k,h=a.width%d,g=0,g=0;0<e.length&&(f=Math.round(Math.max(0,f-h)/d),u=Math.round(Math.max(0,u-n)/k),g=(a.width-h)/d,g=(.5==f?0:f)+(.5==u?0:u)*g+1);l[g]||(l[g]=[]);l[g].push({color:b,gg:c})}if(!a)throw new ReferenceError("new Sprite() -> no image provided.");var e=[],g=[],d=0,k=0,h=0,l=null;this.m=function(){return a};this.o=function(){return a.width};this.w=function(){return a.height};this.N=function(){return d};this.M=
function(){return k};this.j=function(){return 0<e.length};this.$=function(){if(!this.j())return null;var b=h,a=parseInt(h,10),d=g.length;if(1==d)return null;b+=.1;if(b>d)return h=0,1<d?!0:null;if(parseInt(b,10)>a)return h=a+1,!1;h=b;return null};this.ka=function(b,a,f){f=f||0;for(var u=this.o(),n=this.w(),h=0,l=0,m=0,l=0;l<n;l+=a){m=l/a;e[m]=[];for(h=0;h<u;h+=b)e[m][h/b]=new c.b(h+h/b*f,l+l/a*f),u-=f;u=this.o();n-=f}d=b;k=a;g=[1]};this.mb=function(b){b&&b.toString()!=g.toString()&&(g=b,this.Ta())};
this.Ta=function(){0!==m&&(h=0)};this.ab=function(b){if(b){var a=x.createElement("canvas"),d=a.getContext("2d"),e=[],n=null,h=null,k=null,g=null,m=null,r=0,t=0,q=c.g.F,B=0,y=0;l?l.length=0:l=[];a.width=b.width;a.height=b.height;d.drawImage(b,0,0);m=d.getImageData(0,0,b.width,b.height);for(y=m.data.length;B<y;B+=4)h=m.data[B],k=m.data[B+1],g=m.data[B+2],r=B/4,t=Math.floor(r/a.width),r%=a.width,e[t]||(e[t]=[]),255==h&&255==k&&255==g||1>m.data[B+3]?e[t][r]=null:(h=h.toString(16),k=k.toString(16),g=g.toString(16),
h=2>h.length?"0"+h:h,k=2>k.length?"0"+k:k,g=2>g.length?"0"+g:g,e[t][r]="#"+h+k+g);c.forEach(e,function(b){c.forEach(this,function(a){if(0!==q.localeCompare(this)){if(n){f(q,n.width(r));r=n.x();for(y=r+n.width();r<y;r++)for(t=n.y(),m=t+n.height();t<m;t++)e[t][r]=null;n=null}q=this;if(!c.ja(this))return c.g.X;n=new c.u(a.key,b.key);r=1;for(y=b.key+1;;y++){if(!e[y]||e[y][a.key]!=q){n.height(r);break}r++}r=1}else c.ja(q)&&r++})});n&&f(q,n.width(r))}};this.ea=function(){if(!this.j())return 0;var b=parseInt(h,
10);b>g.length&&(b=0);return g[b]||1};this.fa=function(){if(!this.j())return new c.b;var b=this.ea(),a=0;return c.forEach(e,function(){return c.forEach(this,function(){if(++a==b)return this})})}},G:function(a,f,e){var g=null,d=0,k=0,h=null;this.getName=function(){return g};this.o=function(){return d};this.w=function(){return k};this.view=function(a,b,d,e){if(a===m)return h;h=new c.u(a,b,d,e);return this};f!==m&&(g=a,d=f,k=e)},b:function(a,f){var e=0,g=0;this.x=function(a){if(a===m)return e;e=parseFloat(a,
10);return this};this.y=function(a){if(a===m)return g;g=parseFloat(a,10);return this};this.K=function(a){return a instanceof c.b?this.x()==a.x()&&this.y()==a.y():!1};this.v=function(a){if(a instanceof c.b)this.x(a.x()).y(a.y());else throw new TypeError("Point.copy() -> given point is not an instance of Point.");};this.add=function(a,k){return a instanceof c.b?this.x(e+a.x()).y(g+a.y()):this.x(e+(a||0)).y(g+(k||0))};this.Va=function(a){var c=this.x(),e=this.y(),g=a.x(),b=a.y(),f=a.width();a=a.height();
return c>=g&&c<g+f&&e>=b&&e<b+a};a!==m&&(a instanceof c.b?this.v(a):this.x(a).y(f))},u:function(a,f,e,g){var d=new c.b,k=0,h=0;this.position=function(a,b){if(a===m)return d;a instanceof c.b?d.v(a):d.x(a).y(b);return this};this.x=function(a){if(a===m)return d.x();d.x(a);return this};this.y=function(a){if(a===m)return d.y();d.y(a);return this};this.width=function(a){if(a===m)return k;k=parseInt(a,10);return this};this.height=function(a){if(a===m)return h;h=parseInt(a,10);return this};this.da=function(){return new c.b(d.x()+
k/2,d.y()+h/2)};a!==m&&(a instanceof c.u?(this.position(a.position()),this.width(a.width()),this.height(a.height())):a instanceof c.b?(this.position(a),this.width(f),this.height(e)):(this.position(a,f),this.width(e),this.height(g)))},a:{get c(){return{oe:1,sa:2,Ba:3,Aa:4,ta:5,pa:6,wa:7,ua:8,va:9,na:10,ra:11,ma:12,Ea:13,qa:14,xa:15,ya:16}},get f(){return H},get D(){return K},Object:function(){var a=100,f=new c.h("#000"),e="#000",g=0;this.opacity=function(c){if(c===m)return a;a=parseInt(c,10);return this};
this.color=function(a,e){if(!a)return f;f=new c.h(a,e);return this};this.borderColor=function(a,g){if(!a)return e;e=new c.h(a,g);return this};this.I=function(a){if(a===m)return g;g=a;return this};this.i=function(){throw Error("Class \"Drawing.Object\" shouldn't be directly called! You should use an inherited class from this one. Or maybe the inherited class doesn't overwritte the method draw()?");}},u:function(a,f){c.a.Object.call(this);var e=a||1,g=f||1;this.width=function(a){if(a===m)return e;e=
parseInt(a,10);return this};this.height=function(a){if(a===m)return g;g=parseInt(a,10);return this};this.i=function(a,c,h){a.fillRect(c.x(),c.y(),e,g);h&&a.strokeRect(h.x(),h.y(),e,g)}},Md:function(a,f){c.a.Object.call(this);this.I(1);var e=new c.b(a),g=new c.b(f);this.color=function(a,c){return this.borderColor(a,c)};this.i=function(a,c,h){h&&(c=h.x(),h=h.y(),a.beginPath(),a.moveTo(c+e.x(),h+e.y()),a.lineTo(c+g.x(),h+g.y()),a.stroke())}},Tb:function(a){c.a.Object.call(this);this.i=function(c,e,g){c.beginPath();
c.arc(e.x(),e.y(),a,0,360,!1);c.closePath();c.fill();g&&c.stroke()}},Af:function(a){c.a.Object.call(this);var f=a.slice(0);this.i=function(a,g,d){var k=g.x(),h=g.y();a.beginPath();c.forEach(f,function(c){a[0<c.key?"lineTo":"moveTo"](k+this.x(),h+this.y())});a.closePath();a.fill();d&&a.stroke()}},Text:function(a,f,e,g){c.a.Object.call(this);var d=a+""||"",k=f||"20px Calibri",h=parseInt(e,10)||0,l=parseInt(g,10)||20;this.text=function(a){if(a===m)return d;d=a+"";return this};this.font=function(a){if(!a)return k;
k=a;return this};this.maxWidth=function(a){if(a===m)return h;h=parseInt(a,10);return this};this.lineHeight=function(a){if(a===m)return l;l=parseInt(a,10);return this};this.ga=function(){var a=d.split("\n"),e=x.createElement("canvas").getContext("2d");e.textBaseline="top";e.font=k;e.lineWidth=this.I();0<h&&c.forEach(a,function(c){var d=e.measureText(this).width,n="",g=-1,f="",k="",l=[],m=0;if(d>h){l=this.split(" ");m=l.length;do if(f=k,k+=l[++g]+" ",e.measureText(k).width>h||g==m)n+=f+"\n",k=l[g]+
" ";while(g<d);a[c.key]=n}else a[c.key]+="\n"});return a};this.eb=function(){return this.ga().length};this.o=function(){var a=x.createElement("canvas").getContext("2d"),c=0;a.textBaseline="top";a.font=k;a.lineWidth=this.I();c=a.measureText(d).width;return h<c&&0<h?e:c};this.w=function(){return this.eb()*l};this.i=function(a,e,d){var g=d?d.x():0,n=d?d.y():0,h=e.x(),f=e.y();a.font=k;c.forEach(this.ga(),function(c){d&&a.strokeText(this,g,n+c.key*l+l);a.fillText(this,h,f+c.key*l+l)})}},A:function(a){c.a.Object.call(this);
var f=a,e=null;this.C=function(a){if(!a)return f;f=a;return this};this.filter=function(a){if(!a)return e;e=a;return this};this.i=function(a,d){var k=new c.b(0,0),h=f.N(),l=f.M(),b=0,m=0,A=f.m();f.$();f.j()&&k.v(f.fa());b=k.x();m=k.y();a.drawImage(A,b,m,h,l,d.x(),d.y(),h,l);e&&(c.a.f.width=h,c.a.f.height=l,c.a.D.drawImage(A,b,m,h,l,0,0,h,l),e.i(a,d))}},Ic:function(a){c.a.Object.call(this);var f=a||1;this.mode=function(a){if(!a)return f;f=a;return this};this.i=function(a,g){for(var d=c.a.D.getImageData(0,
0,c.a.f.width,c.a.f.height),k=0,h=d.data.length,l=new c.h(this.color()),b=l.ha(),m=function(){switch(f){case c.a.c.ya:return function(a,c,d){return{red:a*b.red/255,green:c*b.green/255,blue:d*b.blue/255}};case c.a.c.sa:return function(a,c,d){return{red:Math.min(255,256*a/(b.red+1)),green:Math.min(255,256*c/(b.green+1)),blue:Math.min(255,256*d/(b.blue+1))}};case c.a.c.Ba:return function(a,c,d){return{red:255-(255-b.red)*(255-a)/255,green:255-(255-b.green)*(255-c)/255,blue:255-(255-b.blue)*(255-d)/255}};
case c.a.c.Aa:return function(a,c,d){return{red:a/255*(a+2*b.red/255*(255-a)),green:c/255*(c+2*b.green/255*(255-c)),blue:d/255*(d+2*b.blue/255*(255-d))}};case c.a.c.ta:return function(a,c,d){return{red:Math.min(255,256*a/(255-b.red+1)),green:Math.min(255,256*c/(255-b.green+1)),blue:Math.min(255,256*d/(255-b.blue+1))}};case c.a.c.pa:return function(a,c,d){return{red:Math.max(0,255-256*(255-a)/(b.red+1)),green:Math.max(0,255-256*(255-c)/(b.green+1)),blue:Math.max(0,255-256*(255-d)/(b.blue+1))}};case c.a.c.wa:return function(a,
c,d){return{red:128<b.red?255-(255-2*(b.red-128))*(255-a)/256:Math.min(255,2*b.red*a/256),green:128<b.green?255-(255-2*(b.green-128))*(255-c)/256:Math.min(255,2*b.green*c/256),blue:128<b.blue?255-(255-2*(b.blue-128))*(255-d)/256:Math.min(255,2*b.blue*d/256)}};case c.a.c.ua:return function(a,c,d){return{red:Math.min(255,Math.max(0,a-b.red+128)),green:Math.min(255,Math.max(0,c-b.green+128)),blue:Math.min(255,Math.max(0,d-b.blue+128))}};case c.a.c.va:return function(a,c,d){return{red:Math.min(255,Math.max(0,
a+b.red-128)),green:Math.min(255,Math.max(0,c+b.green-128)),blue:Math.min(255,Math.max(0,d+b.blue-128))}};case c.a.c.na:return function(a,c,d){return{red:(a+b.red)/2,green:(c+b.green)/2,blue:(d+b.blue)/2}};case c.a.c.ra:return function(a,c,d){return{red:Math.abs(a-b.red),green:Math.abs(c-b.green),blue:Math.abs(d-b.blue)}};case c.a.c.ma:return function(a,c,d){return{red:Math.min(255,a+b.red),green:Math.min(255,c+b.green),blue:Math.min(255,d+b.blue)}};case c.a.c.Ea:return function(a,c,d){return{red:Math.max(0,
a-b.red),green:Math.max(0,c-b.green),blue:Math.max(0,d-b.blue)}};case c.a.c.qa:return function(a,c,d){return{red:Math.min(a,b.red),green:Math.min(c,b.green),blue:Math.min(d,b.blue)}};case c.a.c.xa:return function(a,c,d){return{red:Math.max(a,b.red),green:Math.max(c,b.green),blue:Math.max(d,b.blue)}};default:return function(){return{red:b.red,green:b.green,blue:b.blue}}}}();k<h;k+=4)0<d.data[k+3]&&(l=m(d.data[k],d.data[k+1],d.data[k+2]),d.data[k]=l.red,d.data[k+1]=l.green,d.data[k+2]=l.blue);c.a.D.putImageData(d,
0,0);a.globalAlpha=this.opacity()/100;a.drawImage(c.a.f,0,0,c.a.f.width,c.a.f.height,g.x(),g.y(),c.a.f.width,c.a.f.height)}}},h:function(a,f){function e(){var a=d/255,c=k/255,e=h/255,g=Math.min(a,c,e),f=Math.max(a,c,e),w=f-g,r=0,t=0,x=0;m=(g+f)/2;0===w?b=l=0:(b=.5>m?w/(f+g):w/(2-f-g),r=((f-a)/6+w/2)/w,t=((f-c)/6+w/2)/w,x=((f-e)/6+w/2)/w,a==f?l=x-t:c==f?l=1/3+r-x:e==f&&(l=2/3+t-r),0>l?l+=1:1<l&&--l,l=parseInt(Math.round(360*l),10),b=parseInt(Math.round(100*b),10));m=parseInt(Math.round(100*m),10);
q=null}function g(){var a=m/100,c=l/60,e=b/100*(1-Math.abs(2*a-1)),f=e*(1-Math.abs(c%2-1)),a=a-e/2;0<=c&&1>c?(d=e,k=f,h=0):1<=c&&2>c?(d=f,k=e,h=0):2<=c&&3>c?(d=0,k=e,h=f):3<=c&&4>c?(d=0,k=f,h=e):4<=c&&5>c?(d=f,k=0,h=e):5<=c&&6>c?(d=e,k=0,h=f):h=k=d=0;d=Math.round(255*(d+a));k=Math.round(255*(k+a));h=Math.round(255*(h+a));q=null}var d=0,k=0,h=0,l=0,b=0,m=0,q=null;this.L=function(){if(!q){var a=d.toString(16),b=k.toString(16),c=h.toString(16);q="#"+((2>a.length?"0"+a:a)+(2>b.length?"0"+b:b)+(2>c.length?
"0"+c:c)).toLowerCase()}return q};this.ha=function(){return{red:d,green:k,blue:h}};this.Oa=function(){return{Sa:l,ib:b,$a:m}};this.K=function(a){return a?a.L?this.L()==a.L():!1:!1};if(a instanceof Array)f?(l=a[0],b=a[1],m=a[2],g()):(d=a[0],k=a[1],h=a[2],e());else if(a instanceof c.h)d=a.ha(),k=d.green,h=d.blue,d=d.red,l=a.Oa(),b=l.ib,m=l.$a,l=l.Sa;else{a=a.toUpperCase();if(c.h.za[a])a=c.h.za[a];else if("#"!=a.charAt(0))throw Error('new Color() -> color "'+a+'" is not a valid color.');a=a.substr(1).toLowerCase();
3==a.length?(d=parseInt(a.charAt(0)+a.charAt(0),16),k=parseInt(a.charAt(1)+a.charAt(1),16),h=parseInt(a.charAt(2)+a.charAt(2),16)):(d=parseInt(a.charAt(0)+a.charAt(1),16),k=parseInt(a.charAt(2)+a.charAt(3),16),h=parseInt(a.charAt(4)+a.charAt(5),16));e()}}};Object.defineProperty(c.h,"NAMES",{get:function(){return{sb:"#f0f8ff",ub:"#faebd7",vb:"#0ff",wb:"#7fffd4",xb:"#f0ffff",zb:"#f5f5dc",Ab:"#ffe4c4",Bb:"#000",Cb:"#ffebcd",Db:"#00f",Eb:"#8a2be2",Fb:"#a52a2a",Gb:"#deb887",Ib:"#5f9ea0",Kb:"#7fff00",Lb:"#d2691e",
Nb:"#ff7f50",Ob:"#6495ed",Pb:"#fff8dc",Qb:"#dc143c",Sb:"#0ff",Vb:"#00008b",Wb:"#008b8b",Xb:"#b8860b",Yb:"#a9a9a9",$b:"#a9a9a9",Zb:"#006400",ac:"#bdb76b",bc:"#8b008b",cc:"#556b2f",dc:"#ff8c00",ec:"#9932cc",fc:"#8b0000",gc:"#e9967a",hc:"#8fbc8f",ic:"#483d8b",jc:"#2f4f4f",kc:"#2f4f4f",lc:"#00ced1",mc:"#9400d3",wc:"#ff1493",xc:"#00bfff",yc:"#696969",zc:"#696969",Ac:"#1e90ff",Ec:"#b22222",Fc:"#fffaf0",Gc:"#228b22",Hc:"#f0f",Kc:"#dcdcdc",Lc:"#f8f8ff",Mc:"#ffd700",Nc:"#daa520",Oc:"#808080",Rc:"#808080",
Pc:"#008000",Qc:"#adff2f",Uc:"#f0fff0",Vc:"#ff69b4",fd:"#cd5c5c",gd:"#4b0082",hd:"#fffff0",nd:"#f0e68c",pd:"#e6e6fa",qd:"#fff0f5",rd:"#7cfc00",td:"#fffacd",ud:"#add8e6",vd:"#f08080",wd:"#e0ffff",xd:"#fafad2",yd:"#d3d3d3",Ad:"#d3d3d3",zd:"#90ee90",Bd:"#ffb6c1",Cd:"#ffa07a",Dd:"#20b2aa",Ed:"#87cefa",Fd:"#778899",Gd:"#778899",Hd:"#b0c4de",Id:"#ffffe0",Jd:"#0f0",Kd:"#32cd32",Ld:"#faf0e6",Od:"#f0f",Pd:"#800000",Qd:"#66cdaa",Rd:"#0000cd",Sd:"#ba55d3",Td:"#9370db",Ud:"#3cb371",Vd:"#7b68ee",Wd:"#00fa9a",
Xd:"#48d1cc",Yd:"#c71585",Zd:"#191970",$d:"#f5fffa",ae:"#ffe4e1",be:"#ffe4b5",me:"#ffdead",ne:"#000080",re:"#fdf5e6",se:"#808000",te:"#6b8e23",ue:"#ffA500",ve:"#ff4500",we:"#da70d6",ye:"#eee8aa",ze:"#98fb98",Ae:"#afeeee",Be:"#db7093",Ce:"#ffefd5",De:"#ffdab9",Ee:"#cd853f",Fe:"#ffc0cb",Ge:"#dda0dd",He:"#b0e0e6",Ie:"#800080",Ke:"#f00",Pe:"#bc8f8f",Qe:"#4169e1",Se:"#8b4513",Te:"#fa8072",Ue:"#f4a460",Ve:"#2e8b57",We:"#fff5ee",Ye:"#a0522d",Ze:"#c0c0c0",$e:"#87ceeb",af:"#6a5acd",bf:"#708090",cf:"#708090",
of:"#fffafa",qf:"#00ff7f",zf:"#4682b4",Df:"#d2b48c",Ef:"#008080",Ff:"#d8bfd8",Hf:"#ff6347",If:"#40e0D0",Nf:"#ee82ee",Qf:"#f5deb3",Rf:"#fff",Sf:"#f5f5f5",Vf:"#ff0",Wf:"#9acd32"}}});C.kd=c})(window,document);